### PR TITLE
[Rails 5] Prevent `non-sanitized request parameters!` errors

### LINKED ISSUE #5074: [Rails 5] Fix "non-sanitized params" errors
Required by #3969 

```
When searching should not strip quotes from quoted query
    Failure/Error: url = url_for(routing_info)

    ArgumentError:
      Attempting to generate a URL from non-sanitized request parameters! An attacker can inject malicious data into the generated URL, such as changing the host. Whitelist and sanitize passed parameters to be secure.
    # /home/vagrant/bundle/ruby/2.3.0/gems/actionpack-5.0.7/lib/action_dispatch/routing/url_for.rb:176:in `url_for'
    # ./app/helpers/link_to_helper.rb:236:in `search_url'
    # ./app/controllers/general_controller.rb:81:in `search_redirect'


    ./spec/integration/search_request_spec.rb:13
```

```
RequestController when handling prominence when the request is requester_only should not cache an attachment when showing an attachment to the requester
  Failure/Error: path = url_for(param)

  ArgumentError:
    Attempting to generate a URL from non-sanitized request parameters! An attacker can inject malicious data into the generated URL, such as changing the host. Whitelist and sanitize passed parameters to be secure.
  # /home/vagrant/bundle/ruby/2.3.0/gems/actionpack-5.0.7/lib/action_dispatch/routing/url_for.rb:176:in `url_for'
  # ./app/controllers/application_controller.rb:212:in `foi_fragment_cache_part_path'
  # ./app/controllers/application_controller.rb:220:in `foi_fragment_cache_path'
  # ./app/controllers/request_controller.rb:610:in `cache_attachments'
  # /home/vagrant/bundle/ruby/2.3.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:382:in `block in make_lambda'

  # ./spec/controllers/request_controller_spec.rb:797
```

### PR DESCRIPTION
**Pull request by lizconlan**
## Relevant issue(s)

Fixes #5074

## What does this do?

Permits valid parameter key before they're passed into `url_for` 

## Why was this needed?

Avoids Rails 5 raising `ArgumentError: Attempting to generate a URL from non-sanitized request parameters!`

### CODE REVIEW

File: app/helpers/link_to_helper.rb [hunk 1]
```diff
@@ -294,4 +292,9 @@ def message_path(message, options = {})
     message_url(message, options.merge(:only_path => true))
   end
 
+  def sanitize_params(raw_params)
+    unsafe_keys = %w[protocol host]
+    raw_params.reject { |k| unsafe_keys.include?(k) }.permit!
+  end
```
Comment (gbp) [inline app/helpers/link_to_helper.rb]: FWIW - I am not sure we can be 100% sure this returns parameters which have been sanitised in all cases. It works in `current_path_with_locale` because we're using the `path_only` option.

Comment (lizconlan) [reply app/helpers/link_to_helper.rb]: Fair point - although I've seen this [done elsewhere, but with `port` excluded as well](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/18241)

May try to work out what the actual valid search params are and spend a bit more time trying to permit them. Came unstuck with `latest_status` for reasons which escaped me at the time but ... maybe something more like ...

```rb
allowed_keys = %w[query latest_status view combined only_path controller action page]
diff_keys = routing_info.keys - allowed_keys
routing_info.reject { |k| diff_keys.include?(k) }.permit!
```

Sample params:
```
<ActionController::Parameters {
  "query"=>"bob",
  "latest_status"=>["successful"],
  "controller"=>"general",
  "action"=>"search",
  "combined"=>"bob/requests/relevant",
  "only_path"=>true,
  "view"=>nil} permitted: false>
```

File: app/controllers/application_controller.rb [hunk 2]
```diff
@@ -209,6 +209,11 @@ def render_hidden(template='request/hidden', opts = {})
   # URL using the first three digits of the info request id, because we can't
   # have more than 32,000 entries in one directory on an ext3 filesystem.
   def foi_fragment_cache_part_path(param)
+    if rails5?
+      param =
+        param.permit(:incoming_message_id, :part, :file_name, :id,
+                     :only_path, :locale, :skip_cache)
```
Comment (gbp) [inline app/controllers/application_controller.rb]: Unclear where these params are sourced from. If I understand correctly they are from https://github.com/mysociety/alaveteli/blob/develop/config/routes.rb#L123-L130 https://github.com/mysociety/alaveteli/blob/develop/app/controllers/request_controller.rb#L609 and https://github.com/mysociety/alaveteli/blob/develop/app/controllers/request_controller.rb#L679 maybe the commit message could be expanded.

Comment (lizconlan) [reply app/controllers/application_controller.rb]: I think it was finalised by setting a breakpoint and watching what was passed in as a double-check but I've expanded the commit message as follows:

```
The permitted parameter list is derived from:
  We generally expect :locale so that's included here
  The get_attachment and get_attachment_as_html routes specify
    :id, :incoming_message_id, :part, and :file_name
  RequestContoller#cache_attachments
    expects :skip_cache, :only_path
```

**Comment by lizconlan** [comment]
Uh, I think i managed to merge this on GitHub by mistake by fat-fingering the buttons on HuBoard. Sorry!
