### PR TITLE
[#2508] hotfix bad uudecode

### LINKED ISSUE #2508: Error on trying to parse uuencoded mail when uudecode fails
```
External Command: Error from command "uudecode -o /dev/stdout /tmp/foiuu20150530-14811-u6j936":
uudecode: /tmp/foiuu20150530-14811-u6j936: No `end' line

/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/app/models/incoming_message.rb:525:in `digest'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/app/models/incoming_message.rb:525:in `hexdigest'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/app/models/incoming_message.rb:525:in `block in _uudecode_and_save_attachments'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/app/models/incoming_message.rb:508:in `each'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/app/models/incoming_message.rb:508:in `_uudecode_and_save_attachments'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/app/models/incoming_message.rb:572:in `extract_attachments!'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/app/models/incoming_message.rb:120:in `block in parse_raw_email!'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/app/models/incoming_message.rb:119:in `parse_raw_email!'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/app/models/incoming_message.rb:538:in `get_attachments_for_display'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/app/models/incoming_message.rb:746:in `get_present_file_extensions'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/app/models/info_request_event.rb:227:in `filetype'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/lib/acts_as_xapian/acts_as_xapian.rb:833:in `single_xapian_value'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/lib/acts_as_xapian/acts_as_xapian.rb:826:in `xapian_value'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/lib/acts_as_xapian/acts_as_xapian.rb:926:in `block in xapian_index'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/lib/acts_as_xapian/acts_as_xapian.rb:925:in `each'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/lib/acts_as_xapian/acts_as_xapian.rb:925:in `xapian_index'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/lib/acts_as_xapian/acts_as_xapian.rb:651:in `block (2 levels) in update_index'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/lib/acts_as_xapian/acts_as_xapian.rb:634:in `block in update_index'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/lib/acts_as_xapian/acts_as_xapian.rb:631:in `each'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/lib/acts_as_xapian/acts_as_xapian.rb:631:in `update_index'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/lib/acts_as_xapian/tasks/xapian.rake:12:in `block (2 levels) in <top (required)>'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/bin/rake:23:in `load'
/data/vhost/www.whatdotheyknow.com/alaveteli-2015-05-29T14-26-34/vendor/bundle/ruby/1.9.1/bin/rake:23:in `<main>'
FAILED ActsAsXapian.update_index job 40503534 can't convert nil into String model InfoRequestEvent id 1404333
```

### PR DESCRIPTION
**Pull request by garethrees**
Fixes #2508

### CODE REVIEW

File: app/models/incoming_message.rb [hunk 1]
```diff
@@ -523,7 +518,7 @@ def _uudecode_and_save_attachments(text)
                 content_type = 'application/octet-stream'
             end
             hexdigest = Digest::MD5.hexdigest(content)
-            attachment = self.foi_attachments.find_or_create_by_hexdigest(hexdigest)
+            attachment = foi_attachments.find_or_create_by_hexdigest(hexdigest)
             attachment.update_attributes(:filename => filename,
                                          :content_type => content_type,
                                          :body => content,
```
Comment (crowbot) [inline app/models/incoming_message.rb]: Removing the assignment of `display_size` in the next line would mean that it gets set correctly via `body=` - can be checked by the addition of a line to the "decodes an attachment where the uudecode program reports a 'No end line' error" spec:

    attachments[1].display_size.should == '123K'

Comment (garethrees) [inline app/models/incoming_message.rb]: Added in 0ad3ef5
