### PR TITLE
[#4631] Use `match_array` in tests when comparing arrays

### LINKED ISSUE #4631: PublicBody.with_tag transient spec failure
```
Failures:
  1) PublicBody.with_tag should returns all authorities
     Failure/Error:
       expect(pbs).to eq([
         public_bodies(:geraldine_public_body),
         public_bodies(:humpadink_public_body),
         public_bodies(:forlorn_public_body),
         public_bodies(:silly_walks_public_body),
         public_bodies(:sensible_walks_public_body),
         public_bodies(:other_public_body)
       ])
       expected: [#<PublicBody id: 2, version: 1, last_edit_editor: "mark", last_edit_comment: "Mark named this stupid...quests_overdue_count: 0, info_requests_visible_classified_count: 0, info_requests_visible_count: 0>]
            got: #<ActiveRecord::Relation [#<PublicBody id: 3, version: 2, last_edit_editor: "francis", last_edit_comm...uests_overdue_count: 3, info_requests_visible_classified_count: 3, info_requests_visible_count: 4>]>
       (compared using ==)
       Diff:
       @@ -1,7 +1,98 @@
       -[#<PublicBody id: 2, version: 1, last_edit_editor: "mark", last_edit_comment: "Mark named this stupid quango.", created_at: "2007-10-24 10:51:01", updated_at: "2018-04-25 12:08:48", home_page: nil, api_key: "1", info_requests_count: 4, disclosure_log: nil, info_requests_successful_count: 0, info_requests_not_held_count: 0, info_requests_overdue_count: 3, info_requests_visible_classified_count: 3, info_requests_visible_count: 4>,
       - #<PublicBody id: 3, version: 2, last_edit_editor: "francis", last_edit_comment: "Not sure what this new department does.", created_at: "2007-10-25 10:51:01", updated_at: "2007-10-25 10:51:01", home_page: nil, api_key: "2", info_requests_count: 2, disclosure_log: nil, info_requests_successful_count: 1, info_requests_not_held_count: 0, info_requests_overdue_count: 1, info_requests_visible_classified_count: 2, info_requests_visible_count: 2>,
       - #<PublicBody id: 4, version: 1, last_edit_editor: "robin", last_edit_comment: "Aw, bless.", created_at: "2011-01-26 14:11:02", updated_at: "2011-01-26 14:11:02", home_page: nil, api_key: "3", info_requests_count: 0, disclosure_log: nil, info_requests_successful_count: 0, info_requests_not_held_count: 0, info_requests_overdue_count: 0, info_requests_visible_classified_count: 0, info_requests_visible_count: 0>,
       - #<PublicBody id: 5, version: 1, last_edit_editor: "robin", last_edit_comment: "Is a comment really required?", created_at: "2007-10-25 10:51:01", updated_at: "2007-10-25 10:51:01", home_page: nil, api_key: "4", info_requests_count: 2, disclosure_log: nil, info_requests_successful_count: 2, info_requests_not_held_count: 0, info_requests_overdue_count: 0, info_requests_visible_classified_count: 2, info_requests_visible_count: 2>,
       - #<PublicBody id: 6, version: 1, last_edit_editor: "robin", last_edit_comment: "Another stunning innovation from your friendly nat...", created_at: "2008-10-25 10:51:01", updated_at: "2008-10-25 10:51:01", home_page: nil, api_key: "5", info_requests_count: 1, disclosure_log: nil, info_requests_successful_count: 1, info_requests_not_held_count: 0, info_requests_overdue_count: 0, info_requests_visible_classified_count: 1, info_requests_visible_count: 1>,
       - #<PublicBody id: 7, version: 1, last_edit_editor: "louise", last_edit_comment: "Another edit", created_at: "2008-10-25 10:51:01", updated_at: "2008-10-25 10:51:01", home_page: nil, api_key: "6", info_requests_count: 0, disclosure_log: nil, info_requests_successful_count: 0, info_requests_not_held_count: 0, info_requests_overdue_count: 0, info_requests_visible_classified_count: 0, info_requests_visible_count: 0>]
       +[#<PublicBody:0x0000002fcc4ff0
       +  id: 3,
       +  version: 2,
       +  last_edit_editor: "francis",
       +  last_edit_comment: "Not sure what this new department does.",
       +  created_at: Thu, 25 Oct 2007 10:51:01 UTC +00:00,
       +  updated_at: Thu, 25 Oct 2007 10:51:01 UTC +00:00,
       +  home_page: nil,
       +  api_key: "2",
       +  info_requests_count: 2,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 1,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 1,
       +  info_requests_visible_classified_count: 2,
       +  info_requests_visible_count: 2>,
       + #<PublicBody:0x0000002fcc4e60
       +  id: 4,
       +  version: 1,
       +  last_edit_editor: "robin",
       +  last_edit_comment: "Aw, bless.",
       +  created_at: Wed, 26 Jan 2011 14:11:02 UTC +00:00,
       +  updated_at: Wed, 26 Jan 2011 14:11:02 UTC +00:00,
       +  home_page: nil,
       +  api_key: "3",
       +  info_requests_count: 0,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 0,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 0,
       +  info_requests_visible_classified_count: 0,
       +  info_requests_visible_count: 0>,
       + #<PublicBody:0x0000002fcc4cd0
       +  id: 5,
       +  version: 1,
       +  last_edit_editor: "robin",
       +  last_edit_comment: "Is a comment really required?",
       +  created_at: Thu, 25 Oct 2007 10:51:01 UTC +00:00,
       +  updated_at: Thu, 25 Oct 2007 10:51:01 UTC +00:00,
       +  home_page: nil,
       +  api_key: "4",
       +  info_requests_count: 2,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 2,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 0,
       +  info_requests_visible_classified_count: 2,
       +  info_requests_visible_count: 2>,
       + #<PublicBody:0x0000002fcc4b40
       +  id: 6,
       +  version: 1,
       +  last_edit_editor: "robin",
       +  last_edit_comment:
       +   "Another stunning innovation from your friendly national government",
       +  created_at: Sat, 25 Oct 2008 10:51:01 UTC +00:00,
       +  updated_at: Sat, 25 Oct 2008 10:51:01 UTC +00:00,
       +  home_page: nil,
       +  api_key: "5",
       +  info_requests_count: 1,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 1,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 0,
       +  info_requests_visible_classified_count: 1,
       +  info_requests_visible_count: 1>,
       + #<PublicBody:0x0000002fcc49b0
       +  id: 7,
       +  version: 1,
       +  last_edit_editor: "louise",
       +  last_edit_comment: "Another edit",
       +  created_at: Sat, 25 Oct 2008 10:51:01 UTC +00:00,
       +  updated_at: Sat, 25 Oct 2008 10:51:01 UTC +00:00,
       +  home_page: nil,
       +  api_key: "6",
       +  info_requests_count: 0,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 0,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 0,
       +  info_requests_visible_classified_count: 0,
       +  info_requests_visible_count: 0>,
       + #<PublicBody:0x0000002fcc47f8
       +  id: 2,
       +  version: 1,
       +  last_edit_editor: "mark",
       +  last_edit_comment: "Mark named this stupid quango.",
       +  created_at: Wed, 24 Oct 2007 10:51:01 UTC +00:00,
       +  updated_at: Wed, 25 Apr 2018 12:08:48 UTC +00:00,
       +  home_page: nil,
       +  api_key: "1",
       +  info_requests_count: 4,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 0,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 3,
       +  info_requests_visible_classified_count: 3,
       +  info_requests_visible_count: 4>]
     # ./spec/models/public_body_spec.rb:97:in `block (3 levels) in <top (required)>'
  2) PublicBody.with_tag should returns authorities without categories
     Failure/Error:
       expect(pbs).to eq([
         public_bodies(:geraldine_public_body),
         public_bodies(:humpadink_public_body),
         public_bodies(:silly_walks_public_body),
         public_bodies(:sensible_walks_public_body),
         public_bodies(:other_public_body)
       ])
       expected: [#<PublicBody id: 2, version: 1, last_edit_editor: "mark", last_edit_comment: "Mark named this stupid...quests_overdue_count: 0, info_requests_visible_classified_count: 0, info_requests_visible_count: 0>]
            got: #<ActiveRecord::Relation [#<PublicBody id: 3, version: 2, last_edit_editor: "francis", last_edit_comm...uests_overdue_count: 3, info_requests_visible_classified_count: 3, info_requests_visible_count: 4>]>
       (compared using ==)
       Diff:
       @@ -1,6 +1,82 @@
       -[#<PublicBody id: 2, version: 1, last_edit_editor: "mark", last_edit_comment: "Mark named this stupid quango.", created_at: "2007-10-24 10:51:01", updated_at: "2018-04-25 12:08:48", home_page: nil, api_key: "1", info_requests_count: 4, disclosure_log: nil, info_requests_successful_count: 0, info_requests_not_held_count: 0, info_requests_overdue_count: 3, info_requests_visible_classified_count: 3, info_requests_visible_count: 4>,
       - #<PublicBody id: 3, version: 2, last_edit_editor: "francis", last_edit_comment: "Not sure what this new department does.", created_at: "2007-10-25 10:51:01", updated_at: "2007-10-25 10:51:01", home_page: nil, api_key: "2", info_requests_count: 2, disclosure_log: nil, info_requests_successful_count: 1, info_requests_not_held_count: 0, info_requests_overdue_count: 1, info_requests_visible_classified_count: 2, info_requests_visible_count: 2>,
       - #<PublicBody id: 5, version: 1, last_edit_editor: "robin", last_edit_comment: "Is a comment really required?", created_at: "2007-10-25 10:51:01", updated_at: "2007-10-25 10:51:01", home_page: nil, api_key: "4", info_requests_count: 2, disclosure_log: nil, info_requests_successful_count: 2, info_requests_not_held_count: 0, info_requests_overdue_count: 0, info_requests_visible_classified_count: 2, info_requests_visible_count: 2>,
       - #<PublicBody id: 6, version: 1, last_edit_editor: "robin", last_edit_comment: "Another stunning innovation from your friendly nat...", created_at: "2008-10-25 10:51:01", updated_at: "2008-10-25 10:51:01", home_page: nil, api_key: "5", info_requests_count: 1, disclosure_log: nil, info_requests_successful_count: 1, info_requests_not_held_count: 0, info_requests_overdue_count: 0, info_requests_visible_classified_count: 1, info_requests_visible_count: 1>,
       - #<PublicBody id: 7, version: 1, last_edit_editor: "louise", last_edit_comment: "Another edit", created_at: "2008-10-25 10:51:01", updated_at: "2008-10-25 10:51:01", home_page: nil, api_key: "6", info_requests_count: 0, disclosure_log: nil, info_requests_successful_count: 0, info_requests_not_held_count: 0, info_requests_overdue_count: 0, info_requests_visible_classified_count: 0, info_requests_visible_count: 0>]
       +[#<PublicBody:0x0000002c224440
       +  id: 3,
       +  version: 2,
       +  last_edit_editor: "francis",
       +  last_edit_comment: "Not sure what this new department does.",
       +  created_at: Thu, 25 Oct 2007 10:51:01 UTC +00:00,
       +  updated_at: Thu, 25 Oct 2007 10:51:01 UTC +00:00,
       +  home_page: nil,
       +  api_key: "2",
       +  info_requests_count: 2,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 1,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 1,
       +  info_requests_visible_classified_count: 2,
       +  info_requests_visible_count: 2>,
       + #<PublicBody:0x0000002c2242b0
       +  id: 5,
       +  version: 1,
       +  last_edit_editor: "robin",
       +  last_edit_comment: "Is a comment really required?",
       +  created_at: Thu, 25 Oct 2007 10:51:01 UTC +00:00,
       +  updated_at: Thu, 25 Oct 2007 10:51:01 UTC +00:00,
       +  home_page: nil,
       +  api_key: "4",
       +  info_requests_count: 2,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 2,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 0,
       +  info_requests_visible_classified_count: 2,
       +  info_requests_visible_count: 2>,
       + #<PublicBody:0x0000002c224120
       +  id: 6,
       +  version: 1,
       +  last_edit_editor: "robin",
       +  last_edit_comment:
       +   "Another stunning innovation from your friendly national government",
       +  created_at: Sat, 25 Oct 2008 10:51:01 UTC +00:00,
       +  updated_at: Sat, 25 Oct 2008 10:51:01 UTC +00:00,
       +  home_page: nil,
       +  api_key: "5",
       +  info_requests_count: 1,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 1,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 0,
       +  info_requests_visible_classified_count: 1,
       +  info_requests_visible_count: 1>,
       + #<PublicBody:0x0000002c25ff40
       +  id: 7,
       +  version: 1,
       +  last_edit_editor: "louise",
       +  last_edit_comment: "Another edit",
       +  created_at: Sat, 25 Oct 2008 10:51:01 UTC +00:00,
       +  updated_at: Sat, 25 Oct 2008 10:51:01 UTC +00:00,
       +  home_page: nil,
       +  api_key: "6",
       +  info_requests_count: 0,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 0,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 0,
       +  info_requests_visible_classified_count: 0,
       +  info_requests_visible_count: 0>,
       + #<PublicBody:0x0000002c25fd88
       +  id: 2,
       +  version: 1,
       +  last_edit_editor: "mark",
       +  last_edit_comment: "Mark named this stupid quango.",
       +  created_at: Wed, 24 Oct 2007 10:51:01 UTC +00:00,
       +  updated_at: Wed, 25 Apr 2018 12:08:48 UTC +00:00,
       +  home_page: nil,
       +  api_key: "1",
       +  info_requests_count: 4,
       +  disclosure_log: nil,
       +  info_requests_successful_count: 0,
       +  info_requests_not_held_count: 0,
       +  info_requests_overdue_count: 3,
       +  info_requests_visible_classified_count: 3,
       +  info_requests_visible_count: 4>]
     # ./spec/models/public_body_spec.rb:109:in `block (3 levels) in <top (required)>'
Finished in 18 minutes 21 seconds (files took 11.39 seconds to load)
5493 examples, 2 failures, 7 pending
Failed examples:
rspec ./spec/models/public_body_spec.rb:95 # PublicBody.with_tag should returns all authorities
rspec ./spec/models/public_body_spec.rb:107 # PublicBody.with_tag should returns authorities without categories
Randomized with seed 51845
```

### PR DESCRIPTION
**Pull request by gbp**
#### Relevant issue(s)

Fixes #4631 

#### What does this do?

Hopefully fixes transient spec failures

#### Why was this needed?

Developer happiness

#### Implementation notes

Using `match` fails if the order of the elements are different.

#### Notes to reviewer

I search the project for other array matches, think I've caught them all.

### CODE REVIEW

File: spec/models/has_tag_string_tag_spec.rb [hunk 1]
```diff
@@ -94,7 +94,7 @@ def self.down
       let!(:model_3) { ModelWithTag.create(name: 'a', tag_string: 'foo test') }
 
       it 'sorts by name ASC' do
-        expect(subject).to match([model_3, model_1, model_2])
+        expect(subject).to match_array([model_3, model_1, model_2])
```
Comment (garethrees) [inline spec/models/has_tag_string_tag_spec.rb]: Just a quick early review – This looks like a case where we _do_ care about order, so I don't think a global find and replace is what we want to do.

Comment (gbp) [reply spec/models/has_tag_string_tag_spec.rb]: Ah okay, will revert that change
