### PR TITLE
Prevent empty query param from breaking pages

### LINKED ISSUE #2724: [ERROR] public_body#show (NoMethodError) "undefined method `+' for nil:NilClass"
Some actions break when a query param value is `nil`.

```
A NoMethodError occurred in public_body#show:

  undefined method `+' for nil:NilClass
  lib/xapian_queries.rb:81:in `make_query_from_params'


-------------------------------
Request:
-------------------------------

  * URL       : https://www.whatdotheyknow.com/body/belfast_city_council/awaiting?query
  * IP address: [FILTERED]
  * Parameters: {"query"=>nil, "view"=>"awaiting", "controller"=>"public_body", "action"=>"show", "url_name"=>"belfast_city_council"}
  * Rails root: APP_ROOT/alaveteli-2015-08-05T12-03-07
  * Timestamp : 2015-08-12 19:05:46 +0100

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"[FILTERED]", "locale"=>"en"}

-------------------------------
Environment:
-------------------------------

  * DOCUMENT_ROOT                                  : APP_ROOT/docs
  * HTTP_ACCEPT                                    : text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
  * HTTP_ACCEPT_ENCODING                           : gzip
  * HTTP_FROM                                      : googlebot(at)googlebot.com
  * HTTP_HOST                                      : www.whatdotheyknow.com
  * HTTP_USER_AGENT                                : Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
  * HTTP_X_FORWARDED_FOR                           : [FILTERED]
  * HTTP_X_FORWARDED_PROTO                         : https
  * HTTP_X_REAL_IP                                 : [FILTERED]
  * HTTP_X_SENDFILE_TYPE                           : X-Sendfile
  * HTTP_X_VARNISH                                 : 1756422563
  * ORIGINAL_FULLPATH                              : /body/belfast_city_council/awaiting?query
  * PASSENGER_APP_ENV                              : production
  * PASSENGER_APP_GROUP_NAME                       : APP_ROOT/alaveteli
  * PASSENGER_APP_ROOT                             : APP_ROOT/alaveteli
  * PASSENGER_APP_TYPE                             : rack
  * PASSENGER_CONNECT_PASSWORD                     : [FILTERED]
  * PASSENGER_DEBUGGER                             : false
  * PASSENGER_FRIENDLY_ERROR_PAGES                 : true
  * PASSENGER_MAX_PRELOADER_IDLE_TIME              : -1
  * PASSENGER_MAX_REQUESTS                         : 20000
  * PASSENGER_RESTART_DIR                          :
  * PASSENGER_RUBY                                 : /home/foi/.rbenv/shims/ruby
  * PASSENGER_SHOW_VERSION_IN_HEADER               : true
  * PASSENGER_SPAWN_METHOD                         : direct
  * PASSENGER_STATUS_LINE                          : false
  * PASSENGER_STAT_THROTTLE_RATE                   : 0
  * PATH_INFO                                      : /body/belfast_city_council/awaiting
  * QUERY_STRING                                   : query
  * REMOTE_ADDR                                    : [FILTERED]
  * REMOTE_PORT                                    : 39183
  * REQUEST_METHOD                                 : GET
  * REQUEST_URI                                    : /body/belfast_city_council/awaiting?query
  * SCRIPT_NAME                                    :
  * SCRIPT_URI                                     : http://www.whatdotheyknow.com/body/belfast_city_council/awaiting
  * SCRIPT_URL                                     : /body/belfast_city_council/awaiting
  * SERVER_ADDR                                    : 127.0.0.1
  * SERVER_ADMIN                                   : webmaster@whatdotheyknow.com
  * SERVER_NAME                                    : www.whatdotheyknow.com
  * SERVER_PORT                                    : 80
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : Apache
  * action_controller.instance                     : public_body#show
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x00000007556ed0>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x007f0801e7ed38>
  * action_dispatch.logger                         : #<ActiveSupport::TaggedLogging:0x000000058008e0>
  * action_dispatch.parameter_filter               : [:password, /RAW_POST_DATA/]
  * action_dispatch.remote_ip                      : [FILTERED]
  * action_dispatch.request.content_type           :
  * action_dispatch.request.formats                : [text/html]
  * action_dispatch.request.parameters             : {"query"=>nil, "view"=>"awaiting", "controller"=>"public_body", "action"=>"show", "url_name"=>"belfast_city_council"}
  * action_dispatch.request.path_parameters        : {:view=>"awaiting", :controller=>"public_body", :action=>"show", :url_name=>"belfast_city_council"}
  * action_dispatch.request.query_parameters       : {"query"=>nil}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"[FILTERED]"}
  * action_dispatch.request_id                     : 477b7595f9723fb242423e1e6351f267
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x000000067748f8>
  * action_dispatch.secret_token                   : [FILTERED]
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * newrelic.transaction_started                   : true
  * rack.errors                                    : #<IO:0x00000002610240>
  * rack.hijack                                    : #<Proc:0x007f0801e74388@/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:69 (lambda)>
  * rack.hijack?                                   : true
  * rack.input                                     : #<PhusionPassenger::Utils::TeeInput:0x007f0801e74568>
  * rack.multiprocess                              : true
  * rack.multithread                               : false
  * rack.request.cookie_hash                       : {}
  * rack.request.query_hash                        : {"query"=>nil}
  * rack.request.query_string                      : query
  * rack.run_once                                  : false
  * rack.session                                   : {"session_id"=>"[FILTERED]", "locale"=>"en"}
  * rack.session.options                           : {:path=>"/", :domain=>nil, :expire_after=>nil, :secure=>false, :httponly=>true, :defer=>false, :renew=>false, :secret=>"[FILTERED]", :coder=>#<Rack::Session::Cookie::Base64::Marshal:0x00000006e26b10>, :id=>"[FILTERED]"}
  * rack.url_scheme                                : http
  * rack.version                                   : [1, 2]

  * Process: 20274
  * Server : [FILTERED]

-------------------------------
Backtrace:
-------------------------------

  lib/xapian_queries.rb:81:in `make_query_from_params'
  app/controllers/public_body_controller.rb:60:in `block in show'
  vendor/bundle/ruby/1.9.1/gems/i18n-0.6.11/lib/i18n.rb:256:in `with_locale'
  app/controllers/public_body_controller.rb:32:in `show'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:167:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:591:in `block in _run__2770941039130862874__process_action__4410907610725573606__callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_1132'
  app/controllers/application_controller.rb:117:in `record_memory'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1132'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:590:in `_run__2770941039130862874__process_action__4410907610725573606__callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:17:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `block in instrument'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:28:in `block in process_action'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:361:in `perform_action_with_newrelic_trace'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:27:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:121:in `process'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:45:in `process'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal.rb:203:in `dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_controller/metal.rb:246:in `block in action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:36:in `call'
  vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
  vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
  vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:608:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/exception_notification-3.0.1/lib/exception_notifier.rb:41:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.6/lib/rack/etag.rb:23:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.6/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/head.rb:14:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/flash.rb:242:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.6/lib/rack/session/abstract/id.rb:210:in `context'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.6/lib/rack/session/abstract/id.rb:205:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-ssl-1.3.4/lib/rack/ssl.rb:27:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  lib/whatdotheyknow/strip_empty_sessions.rb:15:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:64:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `_run__4071054767328784381__call__4006188965631269518__callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/rack/logger.rb:32:in `call_app'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `block in call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/tagged_logging.rb:22:in `tagged'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.6/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.6/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.6/lib/rack/lock.rb:15:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.21/lib/action_dispatch/middleware/static.rb:83:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-utf8_sanitizer-1.3.0/lib/rack/utf8_sanitizer.rb:15:in `call'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/engine.rb:484:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/application.rb:231:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
  vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
```

### PR DESCRIPTION
**Pull request by lizconlan**
Unfortunately it looks as though the `query = params.fetch(:query) { '' }` syntax only returns a blank string if the requested key is absent from the params hash. In this case the key is present but empty which is treated as if a null value has been intentionally supplied. Adding a guard to catch the unwanted `nil`

Fixes #2724

### CODE REVIEW

File: lib/xapian_queries.rb [hunk 1]
```diff
@@ -78,6 +78,7 @@ def get_date_range_from_params(params)
 
   def make_query_from_params(params)
     query = params.fetch(:query) { '' }
+    query = '' if query.nil?
```
Comment (garethrees) [inline lib/xapian_queries.rb]: I think you can just make the first line `query = params[:query] || ''`

Comment (lizconlan) [inline lib/xapian_queries.rb]: good point, thanks! I think I need another coffee

Comment (garethrees) [inline lib/xapian_queries.rb]: NP – I just saw this and thought "oops, that line was probably me" :flushed:
