### PR TITLE
Fix hardcoded timestamps in RequestSummary and improve validation

### LINKED ISSUE #4032: AlaveteliPro::RequestSummary should not set default database value for timestamps
https://github.com/mysociety/alaveteli/commit/0bce1d74b5542dc99bebf313aa4d1997ea25e787 adds database default values for `request_created_at` and `request_updated_at`. These values get fixed at the point of migration – not evaluated on record initialisation.

In practice, these default values _should_ get updated by the parent summarisable, but invalid records _can_ be created:

```ruby
Time.zone.now
# => Thu, 08 Jun 2017 12:11:42 BST +01:00
AlaveteliPro::RequestSummary.new.request_created_at
# => Mon, 05 Jun 2017 10:19:11 BST +01:00
```

I think that:

- The default value should be `nil`
- The not null constraint should be kept

```ruby
class RemoveDefaultValueFromRequestCreatedAtAndRequestUpdatedAtToRequestSummary < ActiveRecord::Migration
  def up
    change_column_default :request_summaries, :request_created_at, nil
    change_column_default :request_summaries, :request_updated_at, nil
  end

  def down
    change_column_default :request_summaries, :request_created_at, Time.now
    change_column_default :request_summaries, :request_updated_at, Time.now
  end
end
```

This causes spec failures because now the `AlaveteliPro::RequestSummary` doesn't have values for those attributes.

I had a bit of a stab at this, but it got more complicated than I was expecting. I think the way the two classes (`AlaveteliPro::RequestSummary` and the `Summarisable`) collaborate is a bit strange, but that might just be because I don't have any background knowledge on this.

IMO, this should work:

```ruby
summary = AlaveteliPro::RequestSummary.new
# => #<AlaveteliPro::RequestSummary id: nil, title: nil, body: nil, public_body_names: nil, summarisable_id: nil, summarisable_type: nil, created_at: nil, updated_at: nil, user_id: nil, request_created_at: nil, request_updated_at: nil>
summary.summarisable = InfoRequest.first
# => #<InfoRequest id: 101, …>
summary.save
# ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "request_created_at" violates not-null constraint
# : INSERT INTO "request_summaries" ("created_at", "summarisable_id", "summarisable_type", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"
# from /home/vagrant/bundle/ruby/1.9.1/gems/activerecord-4.1.16/lib/active_record/connection_adapters/postgresql_adapter.rb:834:in `get_last_result'
```

- `RequestSummary` should have presence validators on attributes with not null constraints, so that we don't get a raw SQL error.

Here, I'd have a `before_validation` callback which updates the summary attributes from the related summarisable. I tried this, but ended up getting failures because of duplicate indexes, which I can't really explain:

```ruby
summary.valid?
# => true
summary.save
   (0.4ms)  BEGIN
  SQL (12.3ms)  INSERT INTO "request_summaries" ("created_at", "request_created_at", "request_updated_at", "summarisable_id", "summarisable_type", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["created_at", "2017-06-09 09:53:17.306259"], ["request_created_at", "2007-10-11 18:15:57.000000"], ["request_updated_at", "2017-06-08 16:01:44.179033"], ["summarisable_id", 101], ["summarisable_type", "InfoRequest"], ["updated_at", "2017-06-09 09:53:17.306259"]]
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_request_summaries_on_summarisable"
DETAIL:  Key (summarisable_type, summarisable_id)=(InfoRequest, 101) already exists.
: INSERT INTO "request_summaries" ("created_at", "request_created_at", "request_updated_at", "summarisable_id", "summarisable_type", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"
   (0.3ms)  ROLLBACK
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_request_summaries_on_summarisable"
DETAIL:  Key (summarisable_type, summarisable_id)=(InfoRequest, 101) already exists.
: INSERT INTO "request_summaries" ("created_at", "request_created_at", "request_updated_at", "summarisable_id", "summarisable_type", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"
from /home/vagrant/bundle/ruby/1.9.1/gems/activerecord-4.1.16/lib/active_record/connection_adapters/postgresql_adapter.rb:834:in `get_last_result'
```

I had the same while running specs too, and verified that no `RequestSummary` records existed yet still got the same error – not sure why.

The biggest code smell here IMO, is that `request_summary_spec.rb` has to disable callbacks on various classes. You should be able to test `RequestSummary` without doing this.

```diff
diff --git a/spec/models/alaveteli_pro/request_summary_spec.rb b/spec/models/alaveteli_pro/request_summary_spec.rb
index 785b420..8a85440 100644
--- a/spec/models/alaveteli_pro/request_summary_spec.rb
+++ b/spec/models/alaveteli_pro/request_summary_spec.rb
@@ -8,18 +8,17 @@ RSpec.describe AlaveteliPro::RequestSummary, type: :model do
   # after_save callback. That makes testing this model explicitly hard, so
   # we skip the callback for the duration of these tests.
   before :all do
-    InfoRequest.skip_callback(:save, :after, :create_or_update_request_summary)
-    DraftInfoRequest.skip_callback(:save, :after, :create_or_update_request_summary)
-    InfoRequestBatch.skip_callback(:save, :after, :create_or_update_request_summary)
-    AlaveteliPro::DraftInfoRequestBatch.skip_callback(:save, :after, :create_or_update_request_summary)
-
+    #InfoRequest.skip_callback(:save, :after, :create_or_update_request_summary)
+    #DraftInfoRequest.skip_callback(:save, :after, :create_or_update_request_summary)
+    #InfoRequestBatch.skip_callback(:save, :after, :create_or_update_request_summary)
+    #AlaveteliPro::DraftInfoRequestBatch.skip_callback(:save, :after, :create_or_update_request_summary)
   end

   after :all do
-    InfoRequest.set_callback(:save, :after, :create_or_update_request_summary)
-    DraftInfoRequest.set_callback(:save, :after, :create_or_update_request_summary)
-    InfoRequestBatch.set_callback(:save, :after, :create_or_update_request_summary)
-    AlaveteliPro::DraftInfoRequestBatch.set_callback(:save, :after, :create_or_update_request_summary)
+    #InfoRequest.set_callback(:save, :after, :create_or_update_request_summary)
+    #DraftInfoRequest.set_callback(:save, :after, :create_or_update_request_summary)
+    #InfoRequestBatch.set_callback(:save, :after, :create_or_update_request_summary)
+    #AlaveteliPro::DraftInfoRequestBatch.set_callback(:save, :after, :create_or_update_request_summary)
   end

   it "requires a summarisable" do
@@ -47,7 +46,7 @@ RSpec.describe AlaveteliPro::RequestSummary, type: :model do
         public_body = FactoryGirl.create(:public_body)
         request.title = "Updated title"
         request.public_body = public_body
-        request.save
+        #request.save
         updated_summary = AlaveteliPro::RequestSummary.create_or_update_from(request)
         expect(updated_summary.id).to eq summary.id
         expect(updated_summary.title).to eq request.title
@@ -73,7 +72,7 @@ RSpec.describe AlaveteliPro::RequestSummary, type: :model do
         batch.title = "Updated title"
         batch.body = "Updated body"
         batch.public_bodies << public_body
-        batch.save
+        #batch.save
         updated_summary = AlaveteliPro::RequestSummary.create_or_update_from(batch)
         expect(updated_summary.id).to eq summary.id
         expect(updated_summary.title).to eq batch.title
```

Doing this results in the said key violations:

```
  1) AlaveteliPro::RequestSummary.create_or_update_from when the request already has a summary updates the existing summary from a request
     Failure/Error: summary = FactoryGirl.create(:request_summary)

     ActiveRecord::RecordNotUnique:
       PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_request_summaries_on_summarisable"
       DETAIL:  Key (summarisable_type, summarisable_id)=(InfoRequest, 114) already exists.
       : INSERT INTO "request_summaries" ("body", "created_at", "public_body_names", "summarisable_id", "summarisable_type", "title", "updated_at", "user_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"
```

This is around the point I gave up investigating.

My gut feeling is that:

- `AlaveteliPro::RequestSummaries` shouldn't _create_ records. It should find or build them, and pass the info request to the summary.
- It should use `:autosave => true` on the association to handle the saving of the summary. While this seems similar to what's already happening, I _think_ that the current callback setup is causing some of the strange issues.
- I'm not sure setting `request_created_at` and `request_updated_at` in the factory is a good thing. That might mask issues, since I think we should be using a callback on `RequestSummary` to update from the summarisable before validation. Given the factory sets up a summarisable, setting these should already be handled.

### PR DESCRIPTION
**Pull request by stevenday**
This PR:
- Adds a migration to remove the default value from `request_created_at` and
  `request_updated_at`
- Adds some validation to check that those fields are set
- Adds some additional validation to make clearer the relationship between
  RequestSummaries and the things they summarise.

The latter point involved a slight tweak to the factories to allow us to be
more granular about whether we want to have a unique request summary or not
(as is the case when testing the validation). I've also improved the factory
so that it creates fully valid summaries on create or build.

Fixes #4032

### CODE REVIEW

File: db/migrate/20170621112453_remove_default_value_from_request_created_at_and_request_updated_at_on_request_summary.rb [hunk 1]
```diff
@@ -0,0 +1,12 @@
+# -*- encoding : utf-8 -*-
+class RemoveDefaultValueFromRequestCreatedAtAndRequestUpdatedAtOnRequestSummary < ActiveRecord::Migration
```
Comment (stevenday) [inline db/migrate/20170621112453_remove_default_value_from_request_created_at_and_request_updated_at_on_request_summary.rb]: I purposely ignored this, I don't think it really matters

Comment (crowbot) [inline db/migrate/20170621112453_remove_default_value_from_request_created_at_and_request_updated_at_on_request_summary.rb]: 👍
