### PR TITLE
NotificationMailer transient specs errors

### LINKED ISSUE #4487: Transient spec errors for `NotificationMailer#daily_summary`
Possible related to the changes in https://github.com/mysociety/alaveteli/pull/4383/commits/58152cfe610962dd5c7ad948e46cc8397df4f77e

```
NotificationMailer#daily_summary send the message to the right user
     Failure/Error: info_request.save!
     ActiveRecord::RecordNotUnique:
       PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "info_requests_pkey"
       DETAIL:  Key (id)=(1001) already exists.
       : INSERT INTO "info_requests" ("title", "url_title", "described_state", "user_id", "public_body_id", "info_request_batch_id", "idhash", "created_at", "updated_at", "use_notifications") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"
```

### PR DESCRIPTION
**Pull request by gbp**
Fixes #4487 by not hard coding IDs in the spec file

### CODE REVIEW

File: spec/mailers/notification_mailer_spec.rb [hunk 1]
```diff
@@ -3,56 +3,56 @@
 
 describe NotificationMailer do
   describe '#daily_summary' do
-    let(:user) { FactoryGirl.create(:user) }
+    let(:user) { FactoryGirl.build(:user) }
```
Comment (garethrees) [inline spec/mailers/notification_mailer_spec.rb]: Similar comment to https://github.com/mysociety/alaveteli/pull/4572/commits/154f58bc1d6c293cf6c060b0fe1a4992688925d9 – _why_ can we use build instead of create? I think its the same situation where these built records get saved elsewhere?
