### PR TITLE
[#7293] Update Notable#all_notes

### LINKED ISSUE #7293: Notes set against a `key` do not render when `key:value` is present
On WhatDoTheyKnow, we're considering using the new generalised notes functionality to display messaging on requests, e.g. where a generic event has occurred that effects multiple requests, or where a _right to be forgotten_ indication has arrived from a search engine.

The best way for us to do this, would be to present both a key (e.g. `rtbf`) and a value (e.g. `GDPR/SE/20220910-1`) so that we can tie our internal records together.

It **is** possible to render a note on a request if a key is presented **but** if key _and_ value are presented, a note linked to the key tag **doesn't render on a request**.

### How to reproduce

1. Create a new request in a test authority
2. If one doesn't already exist, create a new note linked to a tag (e.g. `rtbf`)
3. Add the tag to the request via /admin, and note that on the request view, the tag is now present.
4. Amend the tag on the request to key:value format, e.g. `rtbf:test`.
5. Refresh the public view of the request, and note the tag is no longer rendered.

### Expected behaviour
Note should display wherever the tag matches a key that has a note assigned.

### Actual behaviour
Adding the value to the tag removes the note.

### Reproducibility
I have tested this on WDTK requests 651067 and 896135, using note 8296. The former is embargoed, the latter is not. I used [note 8296](https://www.whatdotheyknow.com/admin/tags/rtbf?model_type=InfoRequest), setup against tag `rtbf`.

The issue is always reproducible; it is possible to reverse it by removing `:value` from the tag, but re-adding it will cause the issue to re-appear. This does not appear to be related to a cache.

### Curio
After a value is added to the tag on a request, the request still shows on /admin/tags at key level. E.g. if I tag a request in the format above, it will still show on the admin page for the `rtbf` tag (under requests).

### PR DESCRIPTION
**Pull request by gbp**
## Relevant issue(s)

Fixes #7293

## What does this do?

Update Notable#all_notes

## Why was this needed?

Update the concern so that records tagged with `name:value` will be associated with notes tagged as `name`.

### CODE REVIEW

File: spec/models/concerns/notable_and_taggable.rb [hunk 1]
```diff
@@ -4,12 +4,20 @@
   describe '#all_notes' do
     subject { record.all_notes }
 
-    before { record.tag_string = 'foo' }
+    before { record.tag_string = 'foo:1' }
```
Comment (garethrees) [inline spec/models/concerns/notable_and_taggable.rb:7]: might be worth making this an additional spec so that we're testing both `foo` and `foo:1`?

**Review by garethrees — COMMENTED** [review]
haven't looked in detail but looks good and be good to have this working

File: spec/models/concerns/notable_and_taggable.rb (hunk 1 above)
Comment (gbp) [reply spec/models/concerns/notable_and_taggable.rb]: Yep good shout, I have added this in a fixup.

Before this PR we had:
- PublicBody tagged with "foo:bar" would be associated with a note with tagged with "foo:bar" but not "foo"
- PublicBody tagged with "foo" would be associated with a note with tagged with "foo" but not "foo:bar"

After this PR:
- PublicBody tagged with "foo:bar" would be associated with a note with tagged with "foo:bar" **or** "foo"
- PublicBody tagged with "foo" would be associated with a note with tagged with "foo" but not "foo:bar"


What do you think about that last case... should a PublicBody tagged with "foo" be associated with a note with tagged with "foo:bar".

Comment (garethrees) [reply spec/models/concerns/notable_and_taggable.rb]: > After this PR:
>
> * PublicBody tagged with "foo:bar" would be associated with a note with tagged with "foo:bar" or "foo"
> * PublicBody tagged with "foo" would be associated with a note with tagged with "foo" but not "foo:bar"

This sounds like the correct behaviour to me.
