### PR TITLE
YAML compatibility class

### LINKED ISSUE #5263: [ERROR] admin_request#show (ActionView::Template::Error) "undefined class/module TMail::"
```
An ActionView::Template::Error occurred in admin_request#show:

  undefined class/module TMail::
  app/models/info_request_event.rb:330:in `params'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/admin/requests/122
  * HTTP Method: GET
  * Parameters : {"controller"=>"admin_request", "action"=>"show", "id"=>"122"}
  * Timestamp  : 2019-06-20 12:53:39 +0100

-------------------------------
Backtrace:
-------------------------------

  app/models/info_request_event.rb:330:in `params'
  app/models/info_request_event.rb:343:in `params_diff'
  app/views/admin_request/show.html.erb:250:in `block (2 levels) in _app_views_admin_request_show_html_erb__1851816233347213155_70224032218060'
  app/models/concerns/admin_column.rb:28:in `block in for_admin_column'
  app/models/concerns/admin_column.rb:24:in `each'
  app/models/concerns/admin_column.rb:24:in `for_admin_column'
  app/views/admin_request/show.html.erb:243:in `block in _app_views_admin_request_show_html_erb__1851816233347213155_70224032218060'
  app/views/admin_request/show.html.erb:215:in `_app_views_admin_request_show_html_erb__1851816233347213155_70224032218060'
  app/controllers/application_controller.rb:115:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

### LINKED ISSUE #5265: [ERROR] admin_request#show (ActionView::Template::Error) "undefined class/module PublicBodyTag"
```
An ActionView::Template::Error occurred in admin_request#show:

  undefined class/module PublicBodyTag
  app/models/info_request_event.rb:330:in `params'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/admin/requests/697
  * HTTP Method: GET
  * Parameters : {"controller"=>"admin_request", "action"=>"show", "id"=>"697"}
  * Timestamp  : 2019-06-20 15:49:30 +0100
  * Rails root : [FILTERED]/alaveteli-2019-06-20T14-41-00

-------------------------------
Backtrace:
-------------------------------

  app/models/info_request_event.rb:330:in `params'
  app/models/info_request_event.rb:343:in `params_diff'
  app/views/admin_request/show.html.erb:250:in `block (2 levels) in _app_views_admin_request_show_html_erb__1929189359940310185_69951266522200'
  app/models/concerns/admin_column.rb:28:in `block in for_admin_column'
  app/models/concerns/admin_column.rb:24:in `each'
  app/models/concerns/admin_column.rb:24:in `for_admin_column'
  app/views/admin_request/show.html.erb:243:in `block in _app_views_admin_request_show_html_erb__1929189359940310185_69951266522200'
  app/views/admin_request/show.html.erb:215:in `_app_views_admin_request_show_html_erb__1929189359940310185_69951266522200'
```

### LINKED ISSUE #5463: [ERROR] admin_request#show (ActionView::Template::Error) "not delegated"
```
An ActionView::Template::Error occurred in admin_request#show:

  not delegated
  app/models/info_request_event.rb:340:in `params'

-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/admin/requests/553276
  * HTTP Method: GET
```

### LINKED ISSUE #5464: [ERROR] admin_general#index (ActionView::Template::Error) "undefined method `key?' for nil:NilClass
```
An ActionView::Template::Error occurred in admin_general#index:

  undefined method `key?' for nil:NilClass
  app/models/info_request_event.rb:332:in `block in params'
```

### LINKED ISSUE #5465: [ERROR] admin_general#index (ActionView::Template::Error) "undefined class/module ActiveModel::Type::Text
```
An ActionView::Template::Error occurred in admin_general#index:

  undefined class/module ActiveModel::Type::Text
  app/models/info_request_event.rb:330:in `params'
```

### PR DESCRIPTION
**Pull request by gbp**
## Relevant issue(s)

Fixes #5263 
Fixes #5265 
Fixes #5464 
Fixes #5463
Fixes #5465

## What does this do?

This helps load old InfoRequestEvent instances which contain YAML from
older Rails version or includes old classes which don't exist in the app
any more.

## Why was this needed?

To retain compatibility with old Alaveteli versions.

## Implementation notes

This uses the a similar method to Ruby's `YAML.safe_load` method [1] but we are own `ClassLoader` which can map to different classes instead of restricting which classes can be loaded [2].

[1] https://github.com/ruby/psych/blob/0910ae5575786d57783eafd4d03ebc0d077cd2ed/lib/psych.rb#L352-L360
[2] https://github.com/ruby/psych/blob/0910ae5575786d57783eafd4d03ebc0d077cd2ed/lib/psych/class_loader.rb#L93-L99

### CODE REVIEW

File: spec/lib/yaml_compatability_spec.rb [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+  end
+
+  private
+
+  def yaml_fixture(version)
+    path = File.expand_path(
+      "../fixtures/files/yaml_compatibility_#{version}.yml",
+      __dir__
+    )
+    File.read(path)
```
Comment (garethrees) [inline spec/lib/yaml_compatability_spec.rb]: `load_file_fixture` does this bit for you
