### PR TITLE
[#6414] Fix /version.json

### LINKED ISSUE #6414: [ERROR] general#version (ArgumentError) "wrong number of arguments (given 1, expected 0)"
```
An ArgumentError occurred in general#version:

wrong number of arguments (given 1, expected 0)
app/models/statistics/general.rb:23:in `to_json'


-------------------------------
Request:
-------------------------------

* URL : https://www.whatdotheyknow.com/version.json
* HTTP Method: GET
* Parameters : {"controller"=>"general", "action"=>"version", "format"=>"json"}
* Timestamp : 2021-08-03 01:31:50 +0100
* Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2021-08-02T16-54-49

-------------------------------
Backtrace:
-------------------------------

app/models/statistics/general.rb:23:in `to_json'
app/controllers/general_controller.rb:221:in `block (2 levels) in version'
app/controllers/general_controller.rb:220:in `version'
app/controllers/application_controller.rb:110:in `record_memory'
lib/strip_empty_sessions.rb:14:in `call'
```

### PR DESCRIPTION
**Pull request by garethrees**
## Relevant issue(s)

Fixes #6414

## What does this do?

Allow args given to `Statistics::General#to_json`

## Why was this needed?

Somehow missed this in https://github.com/mysociety/alaveteli/pull/6337 – maybe I didn't reload the Rails server?!

### CODE REVIEW

File: spec/controllers/general_controller_spec.rb [hunk 1]
```diff
@@ -8,13 +8,22 @@
 
     before do
       expect(Statistics::General).to receive(:new).and_return(mock_stats)
+      expect(mock_stats).to receive(:to_json).with(kind_of(Hash))
```
Comment (gbp) [inline spec/controllers/general_controller_spec.rb:11]: with `kind_of(Hash)` is this how Rails calls the method when rendering?

File: spec/controllers/general_controller_spec.rb [hunk 2]
```diff
@@ -8,13 +8,22 @@
...
     end
 
     it 'renders json stats about the install' do
-      get :version, params: { format: :json }
       parsed_body = JSON.parse(response.body).symbolize_keys
       expect(parsed_body).to eq({ foo: 'x', bar: 'y' })
     end
+
+    it 'responds as JSON' do
+      if rails_upgrade?
```
Comment (gbp) [inline spec/controllers/general_controller_spec.rb:21]: 👍 Thanks

**Review by gbp — APPROVED** [review]

File: spec/controllers/general_controller_spec.rb (hunk 1 above)
Comment (garethrees) [reply spec/controllers/general_controller_spec.rb:11]: Yeah – added to commit message in 84207a3 to make this a bit more obvious.
