### PR TITLE
[#6361] Add middleware to handle RangeError raised by Rack

### LINKED ISSUE #6361: [ERROR] attachments#show_as_html (RangeError) "RangeError"
```
A RangeError occurred in attachments#show_as_html:

RangeError
lib/strip_empty_sessions.rb:15:in `call'


-------------------------------
Request:
-------------------------------

ERROR: Failed to generate exception summary:
ActionView::Template::Error: RangeError
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:84:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:113:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:113:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:113:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:113:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:113:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:113:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:113:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:113:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:113:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:118:in `normalize_params'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:71:in `block in parse_nested_query'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:68:in `each'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/query_parser.rb:68:in `parse_nested_query'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/request.rb:590:in `parse_query'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/request.rb:430:in `GET'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/action_dispatch/http/request.rb:368:in `block in GET'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/request.rb:69:in `fetch'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/request.rb:69:in `fetch_header'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/action_dispatch/http/request.rb:367:in `GET'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/action_dispatch/http/parameters.rb:55:in `parameters'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/action_dispatch/http/filter_parameters.rb:43:in `filtered_parameters'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/exception_notification-4.4.3/lib/exception_notifier/views/exception_notifier/_request.text.erb:4:in `__data_vhost_www_whatdotheyknow_com_shared_vendor_bundle_ruby_______gems_exception_notification_______lib_exception_notifier_views_exception_notifier__request_text_erb__116029581734135262_47295935178920'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/template.rb:159:in `block in render'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:170:in `instrument'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/template.rb:354:in `instrument_render_template'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/template.rb:157:in `render'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/renderer/partial_renderer.rb:344:in `block in render_partial'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `block in instrument'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `instrument'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/renderer/partial_renderer.rb:333:in `render_partial'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/renderer/partial_renderer.rb:312:in `render'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/renderer/renderer.rb:49:in `render_partial'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/helpers/rendering_helper.rb:36:in `render'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/exception_notification-4.4.3/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb:9:in `block in __data_vhost_www_whatdotheyknow_com_shared_vendor_bundle_ruby_______gems_exception_notification_______lib_exception_notifier_views_exception_notifier_exception_notification_text_erb___4458263870281976564_47295935083800'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/exception_notification-4.4.3/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb:7:in `map'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/exception_notification-4.4.3/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb:7:in `__data_vhost_www_whatdotheyknow_com_shared_vendor_bundle_ruby_______gems_exception_notification_______lib_exception_notifier_views_exception_notifier_exception_notification_text_erb___4458263870281976564_47295935083800'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/template.rb:159:in `block in render'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:170:in `instrument'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/template.rb:354:in `instrument_render_template'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/template.rb:157:in `render'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `block in instrument'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `instrument'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/renderer/abstract_renderer.rb:43:in `instrument'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/renderer/template_renderer.rb:16:in `render'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/renderer/renderer.rb:44:in `render_template'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/renderer/renderer.rb:25:in `render'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/rendering.rb:103:in `_render_template'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/rendering.rb:84:in `render_to_body'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/abstract_controller/rendering.rb:25:in `render'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.6/lib/action_mailer/base.rb:919:in `block in collect_responses'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.6/lib/action_mailer/collector.rb:28:in `custom'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/abstract_controller/collector.rb:11:in `text'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/exception_notification-4.4.3/lib/exception_notifier/email_notifier.rb:136:in `block in compose_email'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.6/lib/action_mailer/base.rb:920:in `collect_responses'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.6/lib/action_mailer/base.rb:828:in `mail'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/exception_notification-4.4.3/lib/exception_notifier/email_notifier.rb:135:in `compose_email'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/exception_notification-4.4.3/lib/exception_notifier/email_notifier.rb:57:in `exception_notification'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/abstract_controller/base.rb:194:in `process_action'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:98:in `run_callbacks'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/abstract_controller/callbacks.rb:41:in `process_action'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/abstract_controller/base.rb:134:in `process'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.6/lib/action_mailer/rescuable.rb:25:in `block in process'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.6/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.6/lib/action_mailer/rescuable.rb:24:in `process'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionview-5.2.6/lib/action_view/rendering.rb:32:in `process'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.6/lib/action_mailer/base.rb:607:in `block in process'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `block in instrument'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:168:in `instrument'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.6/lib/action_mailer/base.rb:606:in `process'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.6/lib/action_mailer/message_delivery.rb:123:in `block in processed_mailer'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.6/lib/action_mailer/message_delivery.rb:122:in `tap'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.6/lib/action_mailer/message_delivery.rb:122:in `processed_mailer'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.6/lib/action_mailer/message_delivery.rb:113:in `deliver_now'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/exception_notification-4.4.3/lib/exception_notifier/email_notifier.rb:171:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/exception_notification-4.4.3/lib/exception_notifier.rb:162:in `fire_notification'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/exception_notification-4.4.3/lib/exception_notifier.rb:71:in `block in notify_exception'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/exception_notification-4.4.3/lib/exception_notifier.rb:69:in `each'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/exception_notification-4.4.3/lib/exception_notifier.rb:69:in `notify_exception'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/exception_notification-4.4.3/lib/exception_notification/rack.rb:59:in `rescue in call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/exception_notification-4.4.3/lib/exception_notification/rack.rb:48:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-ssl-1.4.1/lib/rack/ssl.rb:27:in `call'
/data/vhost/www.whatdotheyknow.com/alaveteli-2021-06-25T08-53-16/lib/strip_empty_sessions.rb:15:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/callbacks.rb:98:in `run_callbacks'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/rack/logger.rb:38:in `call_app'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/rack/logger.rb:26:in `block in call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:28:in `tagged'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/tagged_logging.rb:71:in `tagged'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/rack/logger.rb:26:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.6/lib/action_dispatch/middleware/executor.rb:14:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/rack-utf8_sanitizer-1.7.0/lib/rack/utf8_sanitizer.rb:22:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/secure_headers-6.3.2/lib/secure_headers/middleware.rb:11:in `call'
/data/vhost/www.whatdotheyknow.com/shared/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

-------------------------------
Backtrace:
-------------------------------

lib/strip_empty_sessions.rb:15:in `call'
```

From the environment, looks like the request was:
```
* REQUEST_URI : /request/552327/response/1424494/attach/html/6/Course%20details%202018%2019%20v1.1.pdf.html%22,%22Course%20details%202018%2019%20v1.1.pdf%22,null,null,null,null,null,false,null,null,%22WhatDoTheyKnow%22,null,null,null,null,null,null,null,null,null,null,null,false,%7B%2226%22:[null,2]%7D],%222008%22:[null,%22Course%20details%202018%2019%20v1.1.pdf%22],%22183836587%22:[%22whatdotheyknow.com%22]%7D],null,[210,70,null,20,21,231,70,-7,-14,null,null,null,true,false,null,null,[]],65,null,null,%22C9kMRRdfyCDZ4M%22,1,null,null,null,null,[[1625905857484585,137625713,1040349831],null,67]],[1,[5,%22G5MeiuND-aEe-M%22,[%22https:/encrypted-tbn0.gstatic.com/images?q%5Cu003dtbn:ANd9GcQ7dKU_SlaOqyJO3YD0dOCfmzsIkyjPevociA%5Cu0026usqp%5Cu003dCAU%22,278,181%5D,%5B%22x-raw-image:///a1f943e38a1e931bbd41605ffa6e85c134b4136353bc4359f019f5632eaddbfc%22,2447,1600%5D,null,0,%22rgb(241,244,241)%22,null,false,%7B%222001%22:%5Bnull,null,null,21,21,15,18,null,null,null,%5B%5D%5D,%222003%22:%5Bnull,%22Ld1mzqp11cQ1oM%22,%22https://library.oapen.org/bitstream/20.500.12657/42655/1/book.pdf%22,%22Communicating%20Science%22,null,null,null,null,null,false,null,null,%22OAPEN%20Library%22,null,null,null,null,null,null,null,null,null,null,null,false,%7B%2226%22:%5Bnull,2%5D%7D%5D,%222008%22:%5Bnull,%22Communicating%20Science%22%5D,%22183836587%22:%5B%22library.oapen.org%22%5D%7D%5D,null,%5B210,195,15,null,null,181,278,null,null,-42,null,null,false,false,null,null,%5B%5D%5D,66,null,null,%22G5MeiuND-aEe-M%22,1,null,null,null,null,%5B%5B1625905857484585,137625713,1040349831%5D,null,68%5D%5D,%5B1,%5B5,%22ISFgRTKFk8XhJM%22,%5B%22https://encrypted-tbn0.gstatic.com/images?q%5Cu003dtbn:ANd9GcQC8lhXMdXlehKB_Wr4IMmF7TxVfsieuHyYpQ%5Cu0026usqp%5Cu003dCAU%22,279,181%5D,%5B%22x-raw-image:///c5938532456021211ea01bad3d2e167d3026b16ee5f5e7ea99e1e5ec37889f91%22,1913,1240%5D,null,0,%22rgb(241,244,222)%22,null,false,%7B%222001%22:%5Bnull,null,null,3,0,0,9,null,null,null,%5B%5D%5D,%222003%22:%5Bnull,%22KzW25_vphpnhoM%22,%22https://link.springer.com/content/pdf/10.1057%2F9781137410634.pdf%22,%22Untitled%22,null,null,null,null,null,false,null,null,%22link.springer.com%22,null,null,null,null,null,null,null,null,null,null,null,false,%7B%2226%22:%5Bnull,2%5D%7D%5D,%222008%22:%5Bnull,%22Untitled%22%5D,%22183836587%22:%5B%22link.springer.com%22%5D%7D%5D,null,%5B145,195,8,null,null,130,201,null,null,-6,null,null,true,false,null,null,%5B%5D%5D,67,null,null,%22ISFgRTKFk8XhJM%22,1,null,null,null,null,%5B%5B1625905857484585,137625713,1040349831%5D,null,69%5D%5D,%5B1,%5B5,%223gCJdR4Cm8HTtM%22,%5B%22https://encrypted-tbn0.gstatic.com/images?q%5Cu003dtbn:ANd9GcQOqzUHpYkBuC5Pij9qFVf0tOtRqgBwPADPSg%5Cu0026usqp%5Cu003dCAU%22,146,346%5D,%5B%22x-raw-image:///c19b021e758900de2e491c247214853c69a1a6ddfec995f641bae1dde35728d0%22,538,1275%5D,null,0,%22rgb(233,236,233)%22,null,false,%7B%222001%22:%5Bnull,null,null,0,0,0,0,null,null,null,%5B%5D%5D,%222003%22:%5Bnull,%22uUXEF8qGAye18M%22,%22http://1.droppdf.com/files/oMNzc/encyclopedia-of-world-literature.pdf%22,%22Gale%20Contextual%20Encyclopedia%20of%20World%20Literature%22,null,null,null,null,null,false,null,null,%22DropPDF%22,null,null,null,null,null,null,null,null,null,null,null,false,%7B%2226%22:%5Bnull,2%5D%7D%5D,%222008%22:%5Bnull,%22Encyclopedia%20of%20World%20Literature%22%5D,%22183836587%22:%5B%221.droppdf.com%22%5D%7D%5D,null,%5B210,89,null,13,14,210,89,null,null,null,null,null,false,false,null,null,%5B%5D%5D,68,null,null,%223gCJdR4Cm8HTtM%22,1,null,null,null,null,%5B%5B1625905857484585,137625713,1040349831%5D,null,70%5D%5D,%5B1,%5B5,%22mGRz-lKAimcyeM%22,%5B%22https://encrypted-tbn0.gstatic.com/images?q%5Cu003dtbn:ANd9GcTN19ttZ3D0seaBZWWdg3qarLT1sGFgtYdniA%5Cu0026usqp%5Cu003dCAU%22,185,273%5D,%5B%22x-raw-image:///678a8052fa73649864cd601f1a2640f6529e7d12c238ac206a072b194fdaaaae%22,716,1058%5D,null,0,%22rgb(208,205,182)%22,null,false,%7B%222001%22:%5Bnull,null,null,0,0,0,0,null,null,null,%5B%5D%5D,%222003%22:%5Bnull,%226xYuSct_3-rQyM%22,%22https://www.historians.org/Documents/Annual/2019/AHA_Annual%20Meeting%202019%20Final_web.pdf%22,%22Untitled%22,null,null,null,null,null,false,null,null,%22American%20Historical%20Association%22,null,null,null,null,null,null,null,null,null,null,null,false,%7B%2226%22:%5Bnull,2%5D%7D%5D,%222008%22:%5Bnull,%22Untitled%22%5D,%22183836587%22:%5B%22historians.org%22%5D%7D%5D,null,%5B145,98,null,9,9,145,98,null,null,null,null,null,true,false,null,null,%5B%5D%5D,69,null,null,%22mGRz-lKAimcyeM%22,1,null,null,null,null,%5B%5B1625905857484585,137625713,1040349831%5D,null,71%5D%5D,%5B1,%5B5,%2204biQ-MUhh5VzM%22,%5B%22https://encrypted-tbn0.gstatic.com/images?q%5Cu003dtbn:ANd9GcQN5MEGhQDM235ITghsvFKKljxKQzqOQo2c7A%5Cu0026usqp%5Cu003dCAU%22,273,185%5D,%5B%22x-raw-image:///1e8614e343e286d3b7eb410d33fa819b84c1973a3ab064802b5eeea7a49b10b8%22,2359,1600%5D,null,0,%22rgb(232,232,232)%22,null,false,%7B%222001%22:%5Bnull,null,null,0,0,0,0,null,null,null,%5B%5D%5D,%222003%22:%5Bnull,%22ExQ0zHsURfwYMM%22,%22https://paperspast.natlib.govt.nz/imageserver/newspapers/P29pZD1DSFAxOTAxMDQyNyZnZXRwZGY9dHJ1ZQ%5Cu003d%5Cu003d%22,%22AND%20%5C%22CO.%22,null,null,null,null,null,false,null,null,%22Papers%20Past%22,null,null,null,null,null,null,null,null,null,null,null,false,%7B%2226%22:%5Bnull,2%5D%7D%5D,%222008%22:%5Bnull,%22AND%20%5C%22CO.%22%5D,%22183836587%22:%5B%22paperspast.natlib.govt.nz%22%5D%7D%5D,null,%5B145,154,21,null,null,104,154,null,null,null,null,null,false,false,null,null,%5B%5D%5D,70,null,null,%2204biQ-MUhh5VzM%22,1,null,null,null,null,%5B%5B1625905857484585,137625713,1040349831%5D,null,72%5D%5D,%5B1,%5B0,%22vwO724qpgdkOqM%22,%5B%22https://encrypted-tbn0.gstatic.com/images?q%5Cu003dtbn:ANd9GcStrbsZQKy6PHIby3GknETJQyCcHfVhtvW61w%5Cu0026usqp%5Cu003dCAU%22,185,272%5D,%5B%22https://crackmap.weebly.com/uploads/1/2/4/8/124884267/201729079.jpg
```

### PR DESCRIPTION
**Pull request by gbp**
## Relevant issue(s)

Fixes #6361

## What does this do?

This Rack middleware will catch the `RangeError` exception, returning a
400 Bad Request response instead.

## Why was this needed?

Rack will raise an `RangeError` when request have parameters which are
nested too deeply. Rack defaults to allow 100 levels deep but this still
isn't enough for some malformed requests resulting in email exception
notifications.

### CODE REVIEW

File: spec/lib/deeply_nested_params_spec.rb [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+  subject { DeeplyNestedParams.new(app) }
+
+  it 'returns 200 response' do
+    status, _headers, _response = subject.call(env)
+    expect(status).to eq(200)
+  end
+
+  context 'if Rack::Utils.parse_query raises an RangeError' do
+    before do
+      allow(Rack::Utils).to receive(:parse_query).and_raise(RangeError)
```
Comment (garethrees) [inline spec/lib/deeply_nested_params_spec.rb:16]: Should try to use known bad data passed to `#call` rather than relying on a stub, in case underlying implementation changes.

**Review by garethrees — CHANGES_REQUESTED** [review]

File: spec/lib/deeply_nested_params_spec.rb (hunk 1 above)
Comment (gbp) [reply spec/lib/deeply_nested_params_spec.rb:16]: Ah I remember now, Rack::Mock actually calls this method so if we attempt to pass in bad params then the `RangeErrror` exception happens too early.

https://github.com/rack/rack/blob/8be612ab949cf2eba7f4231ef17052a68315f911/lib/rack/mock.rb#L129-L130

Comment (garethrees) [reply spec/lib/deeply_nested_params_spec.rb:16]: Ah, annoying. Okay let's go with it as is.

**Review by garethrees — APPROVED** [review]
