### PR TITLE
[#6217] Draft request validation

### LINKED ISSUE #6217: [ERROR] draft_info_requests#create (ActiveRecord::ValueTooLong) "PG::StringDataRightTruncation: ERROR..."
Someone attempted to create a genuine draft with an extremely long title.

```
An ActiveRecord::ValueTooLong occurred in draft_info_requests#create:

PG::StringDataRightTruncation: ERROR: value too long for type character varying(255)
: INSERT INTO "draft_info_requests" ("title", "user_id", "public_body_id", "body", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"
app/controllers/alaveteli_pro/draft_info_requests_controller.rb:10:in `create'



-------------------------------
Request:
-------------------------------

* URL : https://www.asktheeu.org/en/alaveteli_pro/draft_info_requests
* HTTP Method: POST
* Parameters : {"utf8"=>"✓", "authenticity_token"=>"REDACTED", "info_request"=>{"public_body_id"=>"576", "title"=>"VERY_LONG_STRING_REDACTED"}, "outgoing_message"=>{"body"=>"REDACTED"}, "embargo"=>{"embargo_duration"=>""}, "preview"=>"true", "controller"=>"alaveteli_pro/draft_info_requests", "action"=>"create", "locale"=>"en"}
* Timestamp : 2021-04-20 17:53:30 +0200
* Rails root : /REDACTED/eu.alaveteli.org/alaveteli-2021-02-22T08-15-29

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"en",
"user_id"=>4745,
"ttl"=>"2021-04-20T17:53:30.801+02:00",
"remember_me"=>false,
"post_redirect_token"=>"REDACTED",
"_csrf_token"=>"REDACTED"}

-------------------------------
Backtrace:
-------------------------------

app/controllers/alaveteli_pro/draft_info_requests_controller.rb:10:in `create'
app/controllers/application_controller.rb:118:in `record_memory'
lib/strip_empty_sessions.rb:15:in `call'
```

Easy fix here is to add validation to [`DraftInfoRequest`](https://github.com/mysociety/alaveteli/blob/develop/app/models/draft_info_request.rb).

### PR DESCRIPTION
**Pull request by garethrees**
## Relevant issue(s)

Fixes #6217.

## What does this do?

* Extract InfoRequest::TitleValidation concern and use in `InfoRequest` and `InfoRequestBatch`
* Some minor cleanup
* Add `title` validation to `DraftInfoRequest` and `AlaveteliPro::DraftInfoRequestBatch`

## Why was this needed?

Extremely long titles cause unhandled database errors.

## Implementation notes

* Added a somewhat new pattern of defining concern shared examples and explicitly including them in the class under test. Open to suggestion here.
* Not sure about including a concern in a concern (f5076bf).

### CODE REVIEW

File: app/models/concerns/info_request/title_validation.rb [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+  def title_formatting
+    return unless title
+
+    if poorly_formed_title?
+      errors.add(:title, _('Please write the summary using a mixture of ' \
+                           'capital and lower case letters. This makes it ' \
+                           'easier for others to read.'))
+    end
+
+    if generic_foi_title?
```
Comment (garethrees) [inline app/models/concerns/info_request/title_validation.rb:38]: -1 to the rubocop warning here.

Comment (garethrees) [reply app/models/concerns/info_request/title_validation.rb:38]: Well, actually maybe _this_ is nicer:

```diff
diff --git a/app/models/concerns/info_request/title_validation.rb b/app/models/concerns/info_request/title_validation.rb
index beb389268..ea4e3b827 100644
--- a/app/models/concerns/info_request/title_validation.rb
+++ b/app/models/concerns/info_request/title_validation.rb
@@ -28,18 +28,8 @@ module InfoRequest::TitleValidation
 
   def title_formatting
     return unless title
-
-    if poorly_formed_title?
-      errors.add(:title, _('Please write the summary using a mixture of ' \
-                           'capital and lower case letters. This makes it ' \
-                           'easier for others to read.'))
-    end
-
-    if generic_foi_title?
-      errors.add(:title, _('Please describe more what the request is about ' \
-                           'in the subject. There is no need to say it is an ' \
-                           'FOI request, we add that on anyway.'))
-    end
+    errors.add(:title, poorly_formed_title_msg) if poorly_formed_title?
+    errors.add(:title, generic_foi_title_msg) if generic_foi_title?
   end
 
   def title_is_acronym(max_length)
@@ -60,7 +50,19 @@ def well_formed_title?
       title_is_acronym(6)
   end
 
+  def poorly_formed_title_msg
+    _('Please write the summary using a mixture of ' \
+      'capital and lower case letters. This makes it ' \
+      'easier for others to read.')
+  end
+
   def generic_foi_title?
     title =~ /^(FOI|Freedom of Information)\s*requests?$/i
   end
+
+  def generic_foi_title_msg
+    _('Please describe more what the request is about ' \
+      'in the subject. There is no need to say it is an ' \
+      'FOI request, we add that on anyway.')
+  end
 end
```

Could alternatively make the messages constants instead of methods?

Comment (garethrees) [reply app/models/concerns/info_request/title_validation.rb]: I've pushed this version (6c731b0). I think methods _feel_ nicer in this context.

**Review by gbp — APPROVED** [review]
