### PR TITLE
[Rails5] Fix RequestController#get_attachment_as_html

### LINKED ISSUE #5261: [ERROR] Missing partial request/_view_html_stylesheet
```
An ActionView::MissingTemplate occurred in request#get_attachment_as_html:

  Missing partial request/_view_html_stylesheet with {:locale=>[:en], :formats=>[:pdf], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee]}. Searched in:
  * "./lib/themes/whatdotheyknow-theme/lib/views"
  * "./app/views"

  app/controllers/request_controller.rb:689:in `get_attachment_as_html'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/request/246685/response/611823/attach/html/3/Travelcard%20Agreement%201995.pdf
  * HTTP Method: GET
  * Parameters : {"controller"=>"request", "action"=>"get_attachment_as_html", "id"=>"246685", "incoming_message_id"=>"611823", "part"=>"3", "file_name"=>"Travelcard Agreement 1995.pdf"}
  * Timestamp  : 2019-06-19 21:48:20 +0100
```

### PR DESCRIPTION
**Pull request by lizconlan**
## Relevant issue(s)

Fixes #5261 

## What does this do?

* Fixes a spec without an expectation
* Forces `request/request/view_html_stylesheet` to output HTML when called within `RequestController#get_attachment_as_html`
* Code style fixes

## Why was this needed?

Since upgrading to Rails 5.0, the partial will receive a format based on the file extension unless a format is passed in

https://github.com/rails/rails/blob/5-0-stable/actionpack/lib/action_dispatch/http/mime_negotiation.rb#L68-L78

Resulting in an error:

```
An ActionView::MissingTemplate occurred in request#get_attachment_as_html:

  Missing partial request/_view_html_stylesheet with
    {:locale=>[:en], :formats=>[:pdf], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee]}.
```

### CODE REVIEW

File: spec/controllers/request_controller_spec.rb [hunk 1]
```diff
@@ -2939,30 +2939,27 @@ def expect_redirect(status, redirect_path)
...
-    allow(IncomingMessage).to receive(:find).with("44").and_return(incoming_message)
-    allow(IncomingMessage).to receive(:get_attachment_by_url_part_number_and_filename).and_return(attachment)
-    allow(InfoRequest).to receive(:find).with("132").and_return(info_request)
-    params = { :file_name => long_name,
-               :controller => "request",
-               :action => "get_attachment_as_html",
-               :id => "132",
-               :incoming_message_id => "44",
-               :part => "2" }
+    long_name = 'blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah.pdf'
```
Comment (gbp) [inline spec/controllers/request_controller_spec.rb]: This line makes my editor slow to a crawl 😭  
```suggestion
    long_name = 'blah' * 150 + '.pdf'
```

Comment (lizconlan) [reply spec/controllers/request_controller_spec.rb]: good suggestion - one sec
