### PR TITLE
[#2482] Fix translated public body sort

### LINKED ISSUE #2482: Missing letters and incorrect ordering of authoraties
When visisting https://alaveteli-dev.nuug.no/en/body , the Norwegian letters  Æ Ø Å are missing from the list of letters:

  Show only...
  Beginning with
    * A B C D E F G H I J K L M N O P Q R S T U V W X Y Z

The Norwegian letters should have been listed after Z in that list.

Even worse, the ordering of authorities are wrong.  For example "Åfjord Municipality" should be found after "Ytre Helgeland District Psychiatric Centre", and not sorted as an A.

Is there something wrong with our setup?

### PR DESCRIPTION
**Pull request by garethrees**
Fixes #2482 

~~WIP for initial review~~

~~Specs will fail unless nn_NO language is available:~~

```sh
$ sudo apt-get install language-pack-nn
```

##### Todo

- [x] Changelog entry
- [x] Documentation on adding a collation

### CODE REVIEW

**Comment by garethrees** [comment]
https://alaveteli-dev.nuug.no/en/body now seems to be doing the correct thing – following up in #2482

**Comment by garethrees** [comment]
Docs are pretty simple:

```sh
# Install the language pack
$ sudo apt-get install language-pack-nn
```

```sql
-- Create the collations for the language
-- Best to create the language name and the same with a suffix of .utf8,
-- *and* one that matches the alaveteli locale name in APP_ROOT/locale/
CREATE COLLATION "nn_NO" (LOCALE = 'nn_NO.utf8');
CREATE COLLATION "nn_NO.utf8" (LOCALE = 'nn_NO.utf8');
CREATE COLLATION "nn" (LOCALE = 'nn_NO.utf8');
```

File: lib/database_collation.rb [hunk 1]
```diff
@@ -0,0 +1,64 @@
+# Public: Class to check whether the current database supports collation for
```
Comment (crowbot) [inline lib/database_collation.rb]: Could do with an encoding line

File: spec/lib/database_collation_spec.rb [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+  # Connection must be PostgreSQL 90112 or greater
+  default_double_opts = { :adapter_name => 'PostgreSQL',
+                          :postgresql_version => 90112 }
+
+  connection_double_opts = default_double_opts.merge(connection_double_opts)
+
+  connection = double('ActiveRecord::FakeConnection', connection_double_opts)
+
+  installed_collations = [
+    {"collname"=>"default"},
```
Comment (crowbot) [inline spec/lib/database_collation_spec.rb]: Could do with some spacing.
