### PR TITLE
[#5960] Refactor and improve Xapian spec setup

### LINKED ISSUE #5960: Transient spec failure in AlaveteliPro::BatchRequestAuthoritySearchesController#index
https://travis-ci.org/github/mysociety/alaveteli/jobs/742355222

```
Failures:
  1) creating batch requests in alaveteli_pro allows the user to save a draft of a message
     Failure/Error:
       within ".batch-builder__search-results li[data-body-id=\"#{public_body.id}\"]" do
         click_button "Add"
       end
     
     NoMethodError:
       undefined method `id' for nil:NilClass
     # ./spec/integration/alaveteli_dsl.rb:69:in `add_body_to_pro_batch'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:16:in `start_batch_request'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:129:in `block (3 levels) in <top (required)>'
     # ./spec/integration/alaveteli_dsl.rb:106:in `block (2 levels) in using_pro_session'
     # ./spec/integration/alaveteli_dsl.rb:105:in `block in using_pro_session'
     # ./gems/alaveteli_features/lib/alaveteli_features/spec_helpers.rb:7:in `with_feature_enabled'
     # ./spec/integration/alaveteli_dsl.rb:104:in `using_pro_session'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:128:in `block (2 levels) in <top (required)>'
  2) creating batch requests in alaveteli_pro allows the user to create a batch request
     Failure/Error:
       within ".batch-builder__search-results li[data-body-id=\"#{public_body.id}\"]" do
         click_button "Add"
       end
     
     NoMethodError:
       undefined method `id' for nil:NilClass
     # ./spec/integration/alaveteli_dsl.rb:69:in `add_body_to_pro_batch'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:16:in `start_batch_request'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:296:in `block (3 levels) in <top (required)>'
     # ./spec/integration/alaveteli_dsl.rb:106:in `block (2 levels) in using_pro_session'
     # ./spec/integration/alaveteli_dsl.rb:105:in `block in using_pro_session'
     # ./gems/alaveteli_features/lib/alaveteli_features/spec_helpers.rb:7:in `with_feature_enabled'
     # ./spec/integration/alaveteli_dsl.rb:104:in `using_pro_session'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:295:in `block (2 levels) in <top (required)>'
  3) creating batch requests in alaveteli_pro allows the user to save a draft of a message with no embargo
     Failure/Error:
       within ".batch-builder__search-results li[data-body-id=\"#{public_body.id}\"]" do
         click_button "Add"
       end
     
     NoMethodError:
       undefined method `id' for nil:NilClass
     # ./spec/integration/alaveteli_dsl.rb:69:in `add_body_to_pro_batch'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:16:in `start_batch_request'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:158:in `block (3 levels) in <top (required)>'
     # ./spec/integration/alaveteli_dsl.rb:106:in `block (2 levels) in using_pro_session'
     # ./spec/integration/alaveteli_dsl.rb:105:in `block in using_pro_session'
     # ./gems/alaveteli_features/lib/alaveteli_features/spec_helpers.rb:7:in `with_feature_enabled'
     # ./spec/integration/alaveteli_dsl.rb:104:in `using_pro_session'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:157:in `block (2 levels) in <top (required)>'
  4) creating batch requests in alaveteli_pro allows the user to edit a message after previewing it
     Failure/Error:
       within ".batch-builder__search-results li[data-body-id=\"#{public_body.id}\"]" do
         click_button "Add"
       end
     
     NoMethodError:
       undefined method `id' for nil:NilClass
     # ./spec/integration/alaveteli_dsl.rb:69:in `add_body_to_pro_batch'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:16:in `start_batch_request'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:241:in `block (3 levels) in <top (required)>'
     # ./spec/integration/alaveteli_dsl.rb:106:in `block (2 levels) in using_pro_session'
     # ./spec/integration/alaveteli_dsl.rb:105:in `block in using_pro_session'
     # ./gems/alaveteli_features/lib/alaveteli_features/spec_helpers.rb:7:in `with_feature_enabled'
     # ./spec/integration/alaveteli_dsl.rb:104:in `using_pro_session'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:240:in `block (2 levels) in <top (required)>'
  5) creating batch requests in alaveteli_pro allows the user to save a draft even with fields left blank
     Failure/Error:
       within ".batch-builder__search-results li[data-body-id=\"#{public_body.id}\"]" do
         click_button "Add"
       end
     
     NoMethodError:
       undefined method `id' for nil:NilClass
     # ./spec/integration/alaveteli_dsl.rb:69:in `add_body_to_pro_batch'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:16:in `start_batch_request'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:264:in `block (3 levels) in <top (required)>'
     # ./spec/integration/alaveteli_dsl.rb:106:in `block (2 levels) in using_pro_session'
     # ./spec/integration/alaveteli_dsl.rb:105:in `block in using_pro_session'
     # ./gems/alaveteli_features/lib/alaveteli_features/spec_helpers.rb:7:in `with_feature_enabled'
     # ./spec/integration/alaveteli_dsl.rb:104:in `using_pro_session'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:263:in `block (2 levels) in <top (required)>'
  6) creating batch requests in alaveteli_pro provides a template for the users request
     Failure/Error:
       within ".batch-builder__search-results li[data-body-id=\"#{public_body.id}\"]" do
         click_button "Add"
       end
     
     NoMethodError:
       undefined method `id' for nil:NilClass
     # ./spec/integration/alaveteli_dsl.rb:69:in `add_body_to_pro_batch'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:16:in `start_batch_request'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:281:in `block (3 levels) in <top (required)>'
     # ./spec/integration/alaveteli_dsl.rb:106:in `block (2 levels) in using_pro_session'
     # ./spec/integration/alaveteli_dsl.rb:105:in `block in using_pro_session'
     # ./gems/alaveteli_features/lib/alaveteli_features/spec_helpers.rb:7:in `with_feature_enabled'
     # ./spec/integration/alaveteli_dsl.rb:104:in `using_pro_session'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:280:in `block (2 levels) in <top (required)>'
  7) creating batch requests in alaveteli_pro shows errors if the user tries to preview with fields left blank
     Failure/Error:
       within ".batch-builder__search-results li[data-body-id=\"#{public_body.id}\"]" do
         click_button "Add"
       end
     
     NoMethodError:
       undefined method `id' for nil:NilClass
     # ./spec/integration/alaveteli_dsl.rb:69:in `add_body_to_pro_batch'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:16:in `start_batch_request'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:255:in `block (3 levels) in <top (required)>'
     # ./spec/integration/alaveteli_dsl.rb:106:in `block (2 levels) in using_pro_session'
     # ./spec/integration/alaveteli_dsl.rb:105:in `block in using_pro_session'
     # ./gems/alaveteli_features/lib/alaveteli_features/spec_helpers.rb:7:in `with_feature_enabled'
     # ./spec/integration/alaveteli_dsl.rb:104:in `using_pro_session'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:254:in `block (2 levels) in <top (required)>'
  8) creating batch requests in alaveteli_pro allows the user to preview a message before sending
     Failure/Error:
       within ".batch-builder__search-results li[data-body-id=\"#{public_body.id}\"]" do
         click_button "Add"
       end
     
     NoMethodError:
       undefined method `id' for nil:NilClass
     # ./spec/integration/alaveteli_dsl.rb:69:in `add_body_to_pro_batch'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:16:in `start_batch_request'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:208:in `block (3 levels) in <top (required)>'
     # ./spec/integration/alaveteli_dsl.rb:106:in `block (2 levels) in using_pro_session'
     # ./spec/integration/alaveteli_dsl.rb:105:in `block in using_pro_session'
     # ./gems/alaveteli_features/lib/alaveteli_features/spec_helpers.rb:7:in `with_feature_enabled'
     # ./spec/integration/alaveteli_dsl.rb:104:in `using_pro_session'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:207:in `block (2 levels) in <top (required)>'
  9) creating batch requests in alaveteli_pro allows the user to go back and edit the bodies in the batch
     Failure/Error:
       within ".batch-builder__search-results li[data-body-id=\"#{public_body.id}\"]" do
         click_button "Add"
       end
     
     NoMethodError:
       undefined method `id' for nil:NilClass
     # ./spec/integration/alaveteli_dsl.rb:69:in `add_body_to_pro_batch'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:16:in `start_batch_request'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:180:in `block (3 levels) in <top (required)>'
     # ./spec/integration/alaveteli_dsl.rb:106:in `block (2 levels) in using_pro_session'
     # ./spec/integration/alaveteli_dsl.rb:105:in `block in using_pro_session'
     # ./gems/alaveteli_features/lib/alaveteli_features/spec_helpers.rb:7:in `with_feature_enabled'
     # ./spec/integration/alaveteli_dsl.rb:104:in `using_pro_session'
     # ./spec/integration/alaveteli_pro/batch_request_spec.rb:179:in `block (2 levels) in <top (required)>'
  10) creating batch requests in alaveteli_pro allows the user to build a list of authorities
      Failure/Error: expect(page).to have_css(".batch-builder__list__item", count: 25)
        expected #has_css?(".batch-builder__list__item", {:count=>25}) to return true, got false
      # ./spec/integration/alaveteli_pro/batch_request_spec.rb:72:in `block (3 levels) in <top (required)>'
      # ./spec/integration/alaveteli_dsl.rb:106:in `block (2 levels) in using_pro_session'
      # ./spec/integration/alaveteli_dsl.rb:105:in `block in using_pro_session'
      # ./gems/alaveteli_features/lib/alaveteli_features/spec_helpers.rb:7:in `with_feature_enabled'
      # ./spec/integration/alaveteli_dsl.rb:104:in `using_pro_session'
      # ./spec/integration/alaveteli_pro/batch_request_spec.rb:65:in `block (2 levels) in <top (required)>'
  11) AlaveteliPro::BatchRequestAuthoritySearchesController#index when responding to a normal request behaves like creating a search performs a search
      Failure/Error: expect(results.count).to eq 3
      
        expected: 3
             got: 0
      
        (compared using ==)
      Shared Example Group: "creating a search" called from ./spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb:87
      # ./spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb:7:in `block (2 levels) in <top (required)>'
  12) AlaveteliPro::BatchRequestAuthoritySearchesController#index when responding to an ajax request behaves like creating a search performs a search
      Failure/Error: expect(results.count).to eq 3
      
        expected: 3
             got: 0
      
        (compared using ==)
      Shared Example Group: "creating a search" called from ./spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb:118
      # ./spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb:7:in `block (2 levels) in <top (required)>'
Finished in 13 minutes 54 seconds (files took 7.7 seconds to load)
6672 examples, 12 failures, 5 pending
Failed examples:
rspec ./spec/integration/alaveteli_pro/batch_request_spec.rb:127 # creating batch requests in alaveteli_pro allows the user to save a draft of a message
rspec ./spec/integration/alaveteli_pro/batch_request_spec.rb:294 # creating batch requests in alaveteli_pro allows the user to create a batch request
rspec ./spec/integration/alaveteli_pro/batch_request_spec.rb:156 # creating batch requests in alaveteli_pro allows the user to save a draft of a message with no embargo
rspec ./spec/integration/alaveteli_pro/batch_request_spec.rb:239 # creating batch requests in alaveteli_pro allows the user to edit a message after previewing it
rspec ./spec/integration/alaveteli_pro/batch_request_spec.rb:262 # creating batch requests in alaveteli_pro allows the user to save a draft even with fields left blank
rspec ./spec/integration/alaveteli_pro/batch_request_spec.rb:279 # creating batch requests in alaveteli_pro provides a template for the users request
rspec ./spec/integration/alaveteli_pro/batch_request_spec.rb:253 # creating batch requests in alaveteli_pro shows errors if the user tries to preview with fields left blank
rspec ./spec/integration/alaveteli_pro/batch_request_spec.rb:206 # creating batch requests in alaveteli_pro allows the user to preview a message before sending
rspec ./spec/integration/alaveteli_pro/batch_request_spec.rb:178 # creating batch requests in alaveteli_pro allows the user to go back and edit the bodies in the batch
rspec ./spec/integration/alaveteli_pro/batch_request_spec.rb:64 # creating batch requests in alaveteli_pro allows the user to build a list of authorities
rspec ./spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb[1:1:3:1:1] # AlaveteliPro::BatchRequestAuthoritySearchesController#index when responding to a normal request behaves like creating a search performs a search
rspec ./spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb[1:1:4:1:1] # AlaveteliPro::BatchRequestAuthoritySearchesController#index when responding to an ajax request behaves like creating a search performs a search

Randomized with seed 8063

```

### PR DESCRIPTION
**Pull request by gbp**
## Relevant issue(s)

Fixes #5960

## What does this do?

Moves the initial build of the Xapian index to be after the fixture data has been created. This means it’s not done after any RSpec before callbacks or `let!` blocks where other records might be created and indexed and then shared with other specs.

Also improves the interface for the specs so we only ever need to call `update_xapian_index` instead of that and `get_fixtures_xapian_index` to save confusion and reindex multiple times for the same specs.

## Why was this needed?

Fix transient spec failures.

## Implementation notes

I had tried to improve the `load_raw_emails_data` calls as part of this refactor as this seems closely tied to the Xapian indexing but there are still issues with this. I think improvements here could speed up tests as `RawEmail#data=` writes to the disk which is done a lots during our spec suite.

## Notes to reviewer

In the process of developing this change these are some of the RSpec commands which I found were failing - some on fail on develop, some were failing due to changes I had made. All should be passing with this PR.

```
rspec './spec/integration/alaveteli_pro/batch_request_spec.rb[1:2,1:3]' --seed 44794
rspec './spec/controllers/general_controller_spec.rb[5:8]' './spec/lib/user_stats_spec.rb[1:1:1:1]' './spec/script/mailin_spec.rb[1:1]' --seed 64039
rspec './spec/controllers/admin_incoming_message_controller_spec.rb[1:1:3]' './spec/models/xapian_spec.rb[3:3]' './spec/script/mailin_spec.rb[1:1]' --seed 49556
rspec './spec/controllers/admin_incoming_message_controller_spec.rb[1:2:1,1:2:2]' --seed 13241
rspec './spec/controllers/api_controller_spec.rb[1:3:10]' --seed 35838
```

### CODE REVIEW

File: spec/support/xapian_index.rb [hunk 1]
```diff
@@ -25,10 +25,8 @@ def update_xapian_index
 def get_fixtures_xapian_index
   return unless $original_xapian_path
 
-  path_array = $original_xapian_path.split(File::Separator)
-  path_array.pop
-  temp_path = File.join(path_array, 'test.temp')
-  FileUtils.remove_entry_secure(temp_path, force=true)
+  temp_path = File.join(File.dirname($original_xapian_path), 'test.temp')
+  FileUtils.rm_rf(temp_path)
```
Comment (garethrees) [inline spec/support/xapian_index.rb:32]: Why the change from `remove_entry_secure`?

File: spec/controllers/general_controller_spec.rb [hunk 2]
```diff
@@ -275,7 +275,7 @@
   # rebuild xapian index after fixtures loaded
   before(:each) do
     load_raw_emails_data
-    get_fixtures_xapian_index
+    update_xapian_index
```
Comment (garethrees) [inline spec/controllers/general_controller_spec.rb:278]: I think we should note in the commit message that the _reason_ we're doing this is that (AIUI) we now create an initial index, and then after that we only need to reindex based on the new test data added. We're also letting rspec handle the fixture loading.

File: spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb [hunk 3]
```diff
@@ -42,13 +42,6 @@
       session[:user_id] = pro_user.id
     end
 
-    after do
```
Comment (garethrees) [inline spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb:49]: Why are they now unneeded?

**Review by garethrees — COMMENTED** [review]
Nice!! 🕵️ 

Couple of minor questions that I think can be improved by better commit messages, but don't think there's any significant work left here. Excellent work!

File: spec/support/xapian_index.rb (hunk 1 above)
Comment (gbp) [reply spec/support/xapian_index.rb:32]: Update commit message

File: spec/controllers/general_controller_spec.rb (hunk 2 above)
Comment (gbp) [reply spec/controllers/general_controller_spec.rb:220]: Update commit message

File: spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb (hunk 3 above)
Comment (gbp) [reply spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb:49]: Update commit message
