### PR TITLE
[#6046] Fix invalid byte sequence error

### LINKED ISSUE #6046: [ERROR] attachments#show_as_html (Encoding::InvalidByteSequenceError) "\"\\x92\" on ISO-2022-JP
```
An Encoding::InvalidByteSequenceError occurred in attachments#show_as_html:

  "\x92" on ISO-2022-JP
  lib/normalize_string.rb:39:in `encode'

-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/request/180542/response/457167/attach/html/3/Response%20895%2013.pdf.html
  * HTTP Method: GET
  * Parameters : {"controller"=>"attachments", "action"=>"show_as_html", "id"=>"180542", "incoming_message_id"=>"457167", "part"=>"3", "file_name"=>"Response 895 13.pdf.html"}
  * Timestamp  : 2021-01-01 05:22:16 +0000
  * Rails root : /REDACTED/alaveteli-2020-12-17T11-58-46

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"REDACTED", "locale"=>"en"}

-------------------------------
Backtrace:
-------------------------------

  lib/normalize_string.rb:39:in `encode'
  lib/normalize_string.rb:39:in `block in normalize_string_to_utf8'
  lib/normalize_string.rb:31:in `each'
  lib/normalize_string.rb:31:in `normalize_string_to_utf8'
  lib/normalize_string.rb:78:in `convert_string_to_utf8_or_binary'
  lib/mail_handler/backends/mail_backend.rb:89:in `get_part_body'
  lib/mail_handler/backends/mail_backend.rb:371:in `block in get_attachment_attributes'
  lib/mail_handler/backends/mail_backend.rb:370:in `each'
  lib/mail_handler/backends/mail_backend.rb:370:in `get_attachment_attributes'
  app/models/incoming_message.rb:562:in `extract_attachments!'
  app/models/incoming_message.rb:99:in `block in parse_raw_email!'
  app/models/incoming_message.rb:98:in `parse_raw_email!'
  app/models/foi_attachment.rb:94:in `rescue in body'
  app/models/foi_attachment.rb:81:in `body'
  app/models/foi_attachment.rb:109:in `default_body'
  lib/attachment_to_html/adapter.rb:60:in `attachment_body'
  lib/attachment_to_html/adapters/pdf.rb:50:in `convert'
  lib/attachment_to_html/adapters/pdf.rb:32:in `parse_body'
  lib/attachment_to_html/adapter.rb:25:in `body'
  lib/attachment_to_html/adapters/pdf.rb:44:in `number_of_images_in_body'
  lib/attachment_to_html/adapters/pdf.rb:40:in `contains_too_many_images?'
  lib/attachment_to_html/adapters/pdf.rb:25:in `success?'
  lib/attachment_to_html/attachment_to_html.rb:16:in `to_html'
  app/models/foi_attachment.rb:311:in `body_as_html'
  app/controllers/attachments_controller.rb:40:in `show_as_html'
  app/controllers/attachments_controller.rb:137:in `cache_attachments'
  app/controllers/application_controller.rb:113:in `record_memory'
  lib/strip_empty_sessions.rb:15:in `call'
```

### PR DESCRIPTION
**Pull request by gbp**
## Relevant issue(s)

Fixes #6046

## What does this do?

Rescue from `Encoding::InvalidByteSequenceError` same as how we've
recently handled `Encoding::ConverterNotFoundError` [1].

This means for some attachments with the incorrect charset we might
scrub invalid characters. This seems to happen for right single
quotation marks, EG so "don’t" will be displayed as "dont".

This is the same behaviour as other email clients, such as Apple Mail.

[1] https://github.com/mysociety/alaveteli/pull/6451

### CODE REVIEW

File: spec/lib/basic_encoding_spec.rb [hunk 1]
```diff
@@ -19,6 +19,10 @@ def bytes_to_binary_string( bytes, claimed_encoding = nil )
 windows_1258_string = bytes_to_binary_string [ 0x44, 0x4f, 0x4e, 0x47, 0x20,
                                                0xFE, 0x20, 0x44, 0x4f, 0x4e,
                                                0x47 ]
+# 0x92 is invalid
```
Comment (garethrees) [inline spec/lib/basic_encoding_spec.rb:22]: Invalid in any encoding/charset etc, or just invalid UTF8? Might want to be a bit clearer on this comment since this is a very infrequently looked at area of the code!

**Review by garethrees — APPROVED** [review]
Excellent!

File: spec/lib/basic_encoding_spec.rb (hunk 1 above)
Comment (gbp) [reply spec/lib/basic_encoding_spec.rb]: Updated the comment
