### PR TITLE
Destroying and expiring InfoRequest data

### LINKED ISSUE #2400: admin_request#destroy (TypeError) "can't modify frozen hash"
When fully destroying a request on Nicaragua alaveteli through the admin interface:

```
A TypeError occurred in admin_request#destroy:

can't modify frozen hash
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/attribute_methods/write.rb:38:in `[]='

-------------------------------
Request:
-------------------------------

* URL : https://derechoapreguntar.org/admin/requests/33
* Parameters: {"authenticity_token"=>"8ba2D0ghmFH+ZLvASpjUYi33TBpJrspAZgHoQkQzygU=", "id"=>"33", "_method"=>"delete", "commit"=>"Destroy request entirely", "controller"=>"admin_request", "action"=>"destroy", "utf8"=>"✓"}
* Timestamp : 2015-04-30 03:42:13 -0600

-------------------------------
Backtrace:
-------------------------------

vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/attribute_methods/write.rb:38:in `[]='
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/attribute_methods/write.rb:38:in `write_attribute'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/attribute_methods/dirty.rb:67:in `write_attribute'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/attribute_methods/write.rb:14:in `cached_attachment_text_clipped='
app/models/incoming_message.rb:317:in `clear_in_database_caches!'
app/models/info_request.rb:239:in `clear_in_database_caches!'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/associations/collection_proxy.rb:91:in `each'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/associations/collection_proxy.rb:91:in `send'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/associations/collection_proxy.rb:91:in `method_missing'
app/models/info_request.rb:238:in `clear_in_database_caches!'
app/controllers/admin_controller.rb:34:in `expire_for_request'
app/controllers/admin_request_controller.rb:89:in `destroy'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:167:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:10:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:18:in `process_action'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:569:in `_run__607506605__process_action__1854688183__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:215:in `_conditional_callback_around_1115'
app/controllers/application_controller.rb:106:in `record_memory'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1115'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:557:in `_run__607506605__process_action__1854688183__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:17:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/rescue.rb:29:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:23:in `process_action'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:353:in `perform_action_with_newrelic_trace'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:22:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:121:in `process'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:45:in `process'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal.rb:203:in `dispatch'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal.rb:246:in `action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:36:in `call'
vendor/bundle/ruby/1.8/gems/journey-1.0.4/lib/journey/router.rb:68:in `call'
vendor/bundle/ruby/1.8/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
vendor/bundle/ruby/1.8/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:608:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/exception_notification-3.0.1/lib/exception_notifier.rb:41:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/conditionalget.rb:35:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/head.rb:14:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/flash.rb:242:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/cookies.rb:341:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
lib/whatdotheyknow/strip_empty_sessions.rb:14:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:64:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:28:in `call'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `_run__1561311642__call__4__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/rack/logger.rb:32:in `call_app'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/tagged_logging.rb:22:in `tagged'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/request_id.rb:22:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/static.rb:83:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/engine.rb:484:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/application.rb:231:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `send'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:449:in `initialize'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:449:in `new'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:449:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `times'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:447:in `synchronize'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:447:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:208:in `main_loop'
/usr/share/passenger/helper-scripts/rack-loader.rb:133
```

### LINKED ISSUE #2401: PG::ForeignKeyViolation occurred in admin_request#destroy
When fully destroying a request in the admin interface of nicaragua alaveteli

```
A PG::ForeignKeyViolation occurred in admin_request#destroy:

ERROR: update or delete on table "info_requests" violates foreign key constraint "fk_censor_rules_info_request" on table "censor_rules"
DETAIL: Key (id)=(34) is still referenced from table "censor_rules".

vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `get_last_result'

-------------------------------
Request:
-------------------------------

* URL : https://derechoapreguntar.org/admin/requests/34
* Parameters: {"authenticity_token"=>"8ba2D0ghmFH+ZLvASpjUYi33TBpJrspAZgHoQkQzygU=", "id"=>"34", "_method"=>"delete", "commit"=>"Destroy request entirely", "controller"=>"admin_request", "action"=>"destroy", "utf8"=>"✓"}
* Timestamp : 2015-04-30 03:42:41 -0600

-------------------------------
Backtrace:
-------------------------------

vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `get_last_result'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in `exec_cache'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `exec_delete'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `log_without_newrelic_instrumentation'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log_without_newrelic_instrumentation'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/active_record.rb:55:in `log'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/method_tracer.rb:69:in `trace_execution_scoped'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/method_tracer.rb:67:in `trace_execution_scoped'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/active_record.rb:52:in `log'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:670:in `exec_delete'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:101:in `delete'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `delete'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/relation.rb:413:in `delete_all'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/persistence.rb:141:in `destroy'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/locking/optimistic.rb:103:in `destroy'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:254:in `destroy'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:414:in `_run__1754867383__destroy__4__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_destroy_callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:254:in `destroy'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/transactions.rb:254:in `destroy'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/transactions.rb:313:in `with_transaction_returning_status'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/transactions.rb:254:in `destroy'
app/models/info_request.rb:921:in `fully_destroy'
app/controllers/admin_request_controller.rb:87:in `destroy'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:167:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/rendering.rb:10:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:18:in `process_action'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:569:in `_run__607506605__process_action__1854688183__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:215:in `_conditional_callback_around_1115'
app/controllers/application_controller.rb:106:in `record_memory'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1115'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:557:in `_run__607506605__process_action__1854688183__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:17:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/rescue.rb:29:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123:in `instrument'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:23:in `process_action'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:353:in `perform_action_with_newrelic_trace'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:22:in `process_action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:121:in `process'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:45:in `process'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal.rb:203:in `dispatch'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_controller/metal.rb:246:in `action'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:36:in `call'
vendor/bundle/ruby/1.8/gems/journey-1.0.4/lib/journey/router.rb:68:in `call'
vendor/bundle/ruby/1.8/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
vendor/bundle/ruby/1.8/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:608:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/exception_notification-3.0.1/lib/exception_notifier.rb:41:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/conditionalget.rb:35:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/head.rb:14:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/flash.rb:242:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/cookies.rb:341:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
lib/whatdotheyknow/strip_empty_sessions.rb:14:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:64:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:28:in `call'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `_run__1561311642__call__4__callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `send'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/rack/logger.rb:32:in `call_app'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/tagged_logging.rb:22:in `tagged'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/rack/logger.rb:16:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/request_id.rb:22:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/static.rb:83:in `call'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/engine.rb:484:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/application.rb:231:in `call'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `send'
vendor/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
vendor/bundle/ruby/1.8/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:449:in `initialize'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:449:in `new'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:449:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `times'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:447:in `synchronize'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:447:in `start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:208:in `main_loop'
/usr/share/passenger/helper-scripts/rack-loader.rb:133

```

### LINKED ISSUE #2609: InfoRequest#fully_destroy does not fully destroy associations
When destroying associations in `InfoRequest#fully_destroy`, we should call `fully_destroy` on the associated records.

https://github.com/mysociety/alaveteli/blob/f80ce88be644c9e1f5ef7d506d832c875590df4b/app/models/info_request.rb#L924-L927

I haven't looked but I expect other models have the same issue.

### PR DESCRIPTION
**Pull request by lizconlan**
Fixes the destroy dependency chain using Rails' `:dependent => :destroy` rather than manually destroying dependencies in `fully_destroy` methods (fixes #2609)

Attempts to get rid of the `fully_destroy` methods for `InfoRequest` and `IncomingMessage` in favour of `before_destroy` callbacks. (Isolated in their own commits in case these are an "enhancement" too far, but it does clean up the destroy dependencies quite nicely).

Moves the expiry of `InfoRequest` data from the `AdminController` to new `InfoRequest#expire` and `User#expire_requests`methods (the latter calls `InfoRequest#expire` on a specific user's requests).

All of which *should* get rid of the "frozen hash" error (caused by calling `expire` after deleting the request's incoming_messages - fixes #2400) and the various destroy dependency errors (fixes #2401) encountered when admins attempt to delete a request.

The final fixup commit makes CodeClimate happy ([GPA up by 0.01!!](https://codeclimate.com/github/mysociety/alaveteli/compare/2400-fix-destroy-request-bug) \o/) by removing duplications via Extract Method but the result feels a little odd so purposely left as a fixup for ease of reversal.

### CODE REVIEW

File: spec/controllers/admin_request_controller_spec.rb [hunk 1]
```diff
@@ -55,18 +55,21 @@
 
   describe 'when fully destroying a request' do
 
-    it 'expires the file cache for that request' do
```
Comment (crowbot) [inline spec/controllers/admin_request_controller_spec.rb]: Is the removal of this intentional?

File: app/controllers/admin_controller.rb [hunk 2]
```diff
@@ -23,21 +21,7 @@ def show_rails_exceptions?
...
-
-    # Remove the database caches of body / attachment text (the attachment text
-    # one is after privacy rules are applied)
-    info_request.clear_in_database_caches!
-
-    # also force a search reindexing (so changed text reflected in search)
-    info_request.reindex_request_events
-    # and remove from varnish
-    info_request.purge_in_cache
+    info_request.expire
```
Comment (crowbot) [inline app/controllers/admin_controller.rb]: Is there any need to retain `expire_for_request` as a wrapper? Seems like it would be simpler to just call `info_request.expire` wherever it is used.

File: spec/controllers/admin_request_controller_spec.rb (hunk 1 above)
Comment (lizconlan) [inline spec/controllers/admin_request_controller_spec.rb]: AFAICT, the controller can no longer see whether the expire message has been sent

File: spec/controllers/admin_request_controller_spec.rb [hunk 3]
```diff
@@ -55,18 +55,21 @@
...
-      get :destroy, { :id => info_request }
-    end
-
     it 'uses a different flash message to avoid trying to fetch a non existent user record' do
       info_request = info_requests(:external_request)
       post :destroy, { :id => info_request.id }
       expect(request.flash[:notice]).to include('external')
     end
 
+    it 'destroys associated incoming_message records' do
```
Comment (crowbot) [inline spec/controllers/admin_request_controller_spec.rb]: Not sure why this spec is part of this PR?

File: spec/models/info_request_spec.rb [hunk 4]
```diff
@@ -278,6 +278,21 @@
       expect(Comment.where(:id => comment.id)).to be_empty
     end
 
+    it 'can destroy a request with incoming messages' do
```
Comment (crowbot) [inline spec/models/info_request_spec.rb]: Again, not sure why this spec is included in this PR?

File: app/controllers/admin_controller.rb (hunk 2 above)
Comment (lizconlan) [inline app/controllers/admin_controller.rb]: Only to preserve the symmetry of `expire_for_request` vs `expire_for_user`, which may well be a rubbish reason for keeping it

File: spec/controllers/admin_request_controller_spec.rb (hunk 3 above)
Comment (lizconlan) [inline spec/controllers/admin_request_controller_spec.rb]: The "can't modify frozen hash" error was being triggered when attempting to destroy requests with associated incoming messages

Comment (crowbot) [inline spec/controllers/admin_request_controller_spec.rb]: Ah, OK great.

Comment (lizconlan) [inline spec/controllers/admin_request_controller_spec.rb]: Should have written better notes in the PR, sorry

File: spec/controllers/admin_request_controller_spec.rb (hunk 1 above)
Comment (crowbot) [inline spec/controllers/admin_request_controller_spec.rb]: Ah, I think the removal is in the wrong commit then - it should be in b3dfd5d6c303c1d35532c7d6e83d441947f7b4e6 but is in f6777240d7de31c4e39d6ca21bbb8eb6e54e1947

File: app/controllers/admin_controller.rb (hunk 2 above)
Comment (crowbot) [inline app/controllers/admin_controller.rb]: Doesn't seem to me like it's adding any value - arguably `expire_requests_for_user` should be `user.expire_requests`.

Comment (garethrees) [inline app/controllers/admin_controller.rb]: +1, probably worth [deprecating](https://github.com/mysociety/alaveteli/blob/6d397cbd1b4679381504f9cebd00d7b9d4a0dff7/app/models/user.rb#L210-L211) in case someone else is using it.
