### PR TITLE
[#1431] Fix transient spec failure

### LINKED ISSUE #1431: errors_spec fails with seed 58016
``` sh

# First run
# ==============================================================================

$ bin/rake spec SPEC=spec/integration/errors_spec.rb
............FF

Failures:

  1) When errors occur when not considering all requests local in the admin interface should show a full trace for general errors
     Failure/Error: response.body.should have_selector('div[id=traces]')
       expected following output to contain a <div[id=traces]/> tag:
       <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
     # ./spec/integration/errors_spec.rb:136

  2) When errors occur when considering all requests local (by default all in development) should show a full trace for general errors
     Failure/Error: response.body.should have_selector('div[id=traces]')
       expected following output to contain a <div[id=traces]/> tag:
       <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
     # ./spec/integration/errors_spec.rb:32

Finished in 2.08 seconds
14 examples, 2 failures

Failed examples:

rspec ./spec/integration/errors_spec.rb:133 # When errors occur when not considering all requests local in the admin interface should show a full trace for general errors
rspec ./spec/integration/errors_spec.rb:29 # When errors occur when considering all requests local (by default all in development) should show a full trace for general errors

Randomized with seed 58016

rake aborted!
/usr/bin/ruby1.8 -S rspec spec/integration/errors_spec.rb failed

Tasks: TOP => spec
(See full trace by running task with --trace)

# Second run
# ==============================================================================

$ bin/rake spec SPEC=spec/integration/errors_spec.rb
..............

Finished in 2.36 seconds
14 examples, 0 failures

Randomized with seed 37043

# Re-run the first run by passing the seed number
# ==============================================================================

$ bin/rake spec SPEC=spec/integration/errors_spec.rb SPEC_OPTS='--order rand:58016'
............FF

Failures:

  1) When errors occur when not considering all requests local in the admin interface should show a full trace for general errors
     Failure/Error: response.body.should have_selector('div[id=traces]')
       expected following output to contain a <div[id=traces]/> tag:
       <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
     # ./spec/integration/errors_spec.rb:136

  2) When errors occur when considering all requests local (by default all in development) should show a full trace for general errors
     Failure/Error: response.body.should have_selector('div[id=traces]')
       expected following output to contain a <div[id=traces]/> tag:
       <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
     # ./spec/integration/errors_spec.rb:32

Finished in 2.31 seconds
14 examples, 2 failures

Failed examples:

rspec ./spec/integration/errors_spec.rb:133 # When errors occur when not considering all requests local in the admin interface should show a full trace for general errors
rspec ./spec/integration/errors_spec.rb:29 # When errors occur when considering all requests local (by default all in development) should show a full trace for general errors

Randomized with seed 58016

rake aborted!
/usr/bin/ruby1.8 -S rspec spec/integration/errors_spec.rb failed

Tasks: TOP => spec
(See full trace by running task with --trace)
```

### LINKED ISSUE #4346: Transient spec failure: …should show a full trace for general errors
```
$ be rspec --seed=16271 spec/integration/errors_spec.rb

Randomized with seed 16271
............FF

Failures:

  1) When errors occur when not considering all requests local in the admin interface should show a full trace for general errors
     Failure/Error: expect(response.body).to match('<div id="traces"')
       expected "" to match "<div id=\"traces\""
     # ./spec/integration/errors_spec.rb:149:in `block (4 levels) in <top (required)>'

  2) When errors occur when considering all requests local (by default all in development) should show a full trace for general errors
     Failure/Error: expect(response.body).to match('<div id="traces"')
       expected "" to match "<div id=\"traces\""
     # ./spec/integration/errors_spec.rb:39:in `block (3 levels) in <top (required)>'

Finished in 3.63 seconds (files took 12.54 seconds to load)
14 examples, 2 failures

Failed examples:

rspec ./spec/integration/errors_spec.rb:146 # When errors occur when not considering all requests local in the admin interface should show a full trace for general errors
rspec ./spec/integration/errors_spec.rb:36 # When errors occur when considering all requests local (by default all in development) should show a full trace for general errors

Randomized with seed 16271
```

### PR DESCRIPTION
**Pull request by gbp**
## Relevant issue(s)

Fixes #1431 
Fixes #4346

## What does this do?

Fixes: 

```
1) When errors occur when considering all requests local (by default all in development) should show a full trace for general errors
   Failure/Error: expect(response.body).to match('<div id="traces"')
     expected "" to match "<div id=\"traces\""
   # ./spec/integration/errors_spec.rb:39:in `block (3 levels) in <top (required)>'
```

## Why was this needed?

This seems to be one of the most common spec failures.

## Notes to reviewer

All the seeds I've tried, including the ones on the linked issues, now work. I've also ran this in a loop for a while without seeing failures.
```
rspec spec/integration/errors_spec.rb --seed=16271
rspec spec/integration/errors_spec.rb --seed=46014
rspec spec/integration/errors_spec.rb --seed=58016
```

### CODE REVIEW

File: spec/integration/errors_spec.rb [hunk 1]
```diff
@@ -3,20 +3,21 @@
...
-    allow(Rails.application).to receive(:env_config).with(no_args) do
-      method.call.merge(
-        'action_dispatch.show_exceptions' => true,
-        'consider_all_requests_local' => value
-      )
-    end
-    @requests_local = Rails.application.config.consider_all_requests_local
-    Rails.application.config.consider_all_requests_local = value
-  end
+  def set_consider_all_requests_local(value, example)
```
Comment (garethrees) [inline spec/integration/errors_spec.rb]: From the commit message, I don't really understand _why_ this change fixes the problem.

Presumably something to do with setting the values properly rather than stubbing them?

Comment (gbp) [reply spec/integration/errors_spec.rb]: I've split this commit into 1. the fix 13f9b7df81 where I've improved the commit message, 2. refactorings 0503924607, f75db140e2 and 70e8d58ab5.

File: spec/integration/errors_spec.rb [hunk 2]
```diff
@@ -8,18 +8,18 @@ def set_consider_all_requests_local(value)
     config = app.config
     env_config = app.env_config
 
-    allow(app).to receive(:env_config).with(no_args) do
```
Comment (garethrees) [inline spec/integration/errors_spec.rb]: > Prefer toggling the config and restoring the vale after the spec example
> has run.

I can see _what_ this does, but it doesn't explain _why_ it's preferable to do this here.

Comment (gbp) [reply spec/integration/errors_spec.rb]: Until I split the commits up I thought this was necessary to get this working... I left this change as it was otherwise it would mean rewriting the later commits in the branch.
